(function(g){var window=this;'use strict';var CHh=function(a,x,y){g.R(function(D){a.B=g.Wm(x,y);g.Fh(D)})},oT=function(a){a.isActive()||a.start()},q$y=function(a,x){return x?a.captionsInitialState:"CAPTIONS_INITIAL_STATE_UNKNOWN"},dk7=function(a){return g.xY(a)||a.C("web_enable_caption_language_preference_stickiness")},Z0G=function(a,x){var y=new g.qc;
y.languageCode=a.languageCode;y.languageName=a.languageName;y.name=a.name;y.displayName=a.displayName;y.kind=a.kind;y.isDefault=!1;y.T=a.T;y.isTranslateable=a.isTranslateable;y.vssId=a.vssId;y.url=a.url;y.translationLanguage=x;a.xtags&&(y.xtags=a.xtags);a.captionId&&(y.captionId=a.captionId);return y},nMG=function(a,x){var y,D,M;
return g.R(function(N){if(N.T==1)return y=a+"|"+x,g.B(N,g.x_(),2);if(N.T!=3){D=N.B;if(!D)throw g.q7("gct");return g.B(N,g.Ax(D),3)}M=N.B;return N.return(M.get("captions",y))})},vMp=function(a,x,y){nMG(a,x).then(function(D){D&&y(D.trackData,new g.qc(D.metadata))})},lzL=function(a){if(!PHn.test(a))throw Error("'"+a+"' is not a valid hex color");
a.length==4&&(a=a.replace(T1J,"#$1$1$2$2$3$3"));a=a.toLowerCase();a=parseInt(a.slice(1),16);return[a>>16,a>>8&255,a&255]},ksY=function(){var a=void 0;
a=a===void 0?{}:a;var x="suggest_correction"in g.V6s?g.V6s.suggest_correction:"Edit caption";x=x||"";var y={},D;for(D in a){y={uK:y.uK};y.uK=D;var M=function(N){return function(){return String(a[N.uK])}}(y);
x=x.replace(new RegExp("\\$\\{"+y.uK+"\\}","gi"),M);x=x.replace(new RegExp("\\$"+y.uK,"gi"),M)}return x},uzF=function(){return g.gX("yt-player-caption-display-settings")},mkh=function(a){g.Cf.call(this,a);
this.B=new Set},Jp=function(){this.segments=[]},WiJ=function(a,x){var y=g.SS(a.segments,x);
y>=0||y<0&&(-y-1)%2===1||(y=-y-1,y>0&&x-a.segments[y-1]===1&&y<a.segments.length&&a.segments[y]-x===1?(g.x2(a.segments,y),g.x2(a.segments,y-1)):y>0&&x-a.segments[y-1]===1?a.segments[y-1]=x:y<a.segments.length&&a.segments[y]-x===1?a.segments[y]=x:(g.Gj(a.segments,y,0,x),g.Gj(a.segments,y+1,0,x)))},EMh=function(a,x,y,D,M,N){g.A.call(this);
this.policy=a;this.player=x;this.JP=y;this.V=D;this.N=M;this.BJ=N;this.U=new Jp;this.D=-1;this.B=this.J=this.T=null;this.cJ=0;this.Y=new g.Id(this.CP,1E3,this);this.events=new g.zW(this);g.U(this,this.Y);g.U(this,this.events);this.events.Z(x,"SEEK_COMPLETE",this.aP);this.aP();this.CP()},sZF=function(a){return a.T&&a.T.N?a.T.N+a.player.GY()<a.player.getCurrentTime():!1},B1y=function(a,x){if(a.policy.qq&&a.player.sP()){var y=g.MO(x,a.policy,{});
y.set("pot",a.player.sP());y=y.IK()}else y=g.MO(x,a.policy,{}).IK();var D={format:"RAW",withCredentials:!0};if(a.policy.e8){D.method="POST";var M=x.U;M&&Object.keys(M).length>0?D.postBody=g.A0(M,g.w_):D.postBody=(0,g.fJ)([120,0])}a.N&&(D.responseType="arraybuffer");var N=++a.cJ,F=(0,g.lY)();a.B=g.hY(y,D,3,100,-1,function(c){c.errorCode==="net.timeout"&&a.player.AP("capnt",{rn:N++})}).then(function(c){if(a.policy.cIP&&N%100===1){var J=(0,g.lY)();
a.player.AP("caprsp",{rn:N,ms:J-F,kb:(c.xhr.responseText.length/1024).toFixed()})}a:{c=c.xhr;a.hP();if(a.J){var G=!(a.N?c.response:c.responseText)||c.status>=400;if(J=g.cfs(c)){c=g.MO(a.J,a.policy,{});a.J.cI(c,J);B1y(a,a.J);break a}if(G)a.player.AP("capfail",{status:c.status});else{var Q;g.k9("fcb_r",(0,g.lY)(),((Q=a.player.getVideoData())==null?void 0:Q.BJ)||"");Q=a.J.gS[0];J=Q.bY;a.V!=null&&a.D!==J&&(a.N?a.V(c.response,(Q.startTime+a.player.GY())*1E3):a.V(c.responseText,(Q.startTime+a.player.GY())*
1E3),a.D=J)}}a.J=null;a.B=null}}).KB(function(c){a.J=null;
a.B=null;var J;a.player.AP("capfail",{rn:N,status:(J=c.xhr)==null?void 0:J.status})});
a.J=x;WiJ(a.U,a.J.gS[0].bY)},GB=function(a,x){g.Cf.call(this,x);
this.B=a;this.L=x;this.U=null;this.D=!1;this.logger=new g.Kc("caps");this.Y=g.wRG(this.L,this.B)},$kL=function(a,x){var y=[],D;
for(D in a.B.T)if(a.B.T.hasOwnProperty(D)){var M=a.B.T[D];if(g.dE(M,x||null)){var N=M.info.id,F=N,c="."+N,J="",G="";if(M=M.info.captionTrack)N=M.languageCode,F=M.displayName,c=M.vssId,J=M.kind,G=M.id;else{M=N;var Q=g.Q4s.get(M);Q==null&&(Q=hmp[M]||hmp[M.replace(/-/g,"_")],g.Q4s.set(M,Q));M=Q;F=M||F}y.push(new g.qc({id:D,languageCode:N,languageName:F,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:c,kind:J,captionId:G}))}}return y},fzP=function(a,x){return x!=null&&x in a.B.T?a.B.T[x]:null},
gMF=function(a,x,y){var D=[],M;
for(M in a.B.T)if(a.B.T.hasOwnProperty(M)){var N=a.B.T[M];if(g.dE(N,y||null)){var F=N.info.captionTrack;F&&F.languageCode===x&&D.push(N)}}return D.length?D[0]:null},Q7=function(a,x,y,D,M,N,F,c,J,G){var Q=G.isInline()&&!0,S={};
Object.assign(S,x);Object.assign(S,a.params);Object.assign(S,y);var K={};Object.assign(K,x.q0);a.params.q0&&Object.assign(K,a.params.q0);Object.assign(K,y.q0);Q&&(S.windowOpacity=.6,K.backgroundOpacity=0);S.q0=K;var L=S.GM===1,w=[{W:"span",G:"captions-text",X:{style:"word-wrap: normal; display: block;"}}],Z,v,m;(c=c.XR("caption_edit_on_hover")&&((Z=G.getVideoData().getPlayerResponse())==null?void 0:(v=Z.captions)==null?void 0:(m=v.playerCaptionsTracklistRenderer)==null?void 0:m.openTranscriptCommand))&&
w.unshift({W:"button",G:"caption-edit",X:{tabindex:"0","aria-label":ksY()},K:[{W:"svg",X:{fill:"#e3e3e3",height:"100%",viewBox:"5 5 38 38",width:"100%"},K:[{W:"path",X:{d:"M9 39h2.2l24.25-24.25-1.1-1.1-1.1-1.1L9 36.8Zm-3 3v-6.4L35.4 6.2q.85-.85 2.12-.82 1.27.02 2.12.87L41.8 8.4q.85.85.85 2.1t-.85 2.1L12.4 42Zm33.5-31.55L37.45 8.4Zm-4.05 4.3-1.1-1.1-1.1-1.1 2.2 2.2Z"}}]}]});g.O.call(this,{W:"div",G:"caption-window",X:{id:"caption-window-"+a.id,dir:L?"rtl":"ltr",tabindex:"0",lang:S.lang},K:w});var u=
this;this.D=[];this.UJ=!1;this.B=a;this.N1=this.yP=null;this.AK=N;this.Vn=F;this.Y=null;this.maxWidth=N*.96;this.maxHeight=F*.96;this.T=S;this.n1=y;this.dS=x;this.U=this.QP("captions-text");this.O6=this.U.style.getPropertyValue("box-decoration-break")!==""||this.U.style.getPropertyValue("-webkit-box-decoration-break")!=="";this.Cc=Rmn(D,M,N,F);this.Fn=J;c&&(this.N=this.QP("caption-edit"),this.Z(this.N,"click",function(){u.Fn()}));
this.type=0;this.Gt=this.Cc*Y$P(K);this.S8=Q;a=new g.WR(this.element,!0);g.U(this,a);a.subscribe("dragstart",this.qt,this);a.subscribe("dragmove",this.VG,this);a.subscribe("dragend",this.EF,this);this.EJ=this.YG=this.iY=this.zt=0;a="";this.T.windowOpacity&&(a=lzL(this.T.windowColor),a="rgba("+a[0]+","+a[1]+","+a[2]+","+this.T.windowOpacity+")");x={"background-color":a,display:this.T.isVisible===!1?"none":"","text-align":Ais[this.T.textAlign]};this.O6&&(x["border-radius"]=a?this.Gt/8+"px":"");(this.J=
this.B.params.GM===2||this.B.params.GM===3)&&Uks(this,this.element);g.F7(this.element,x);if(Q){var E;(E=this.element.parentElement)==null||E.style.setProperty("--caption-window-color",a)}switch(this.T.uM){case 0:case 1:case 2:g.zt(this.element,"ytp-caption-window-top");break;case 6:case 7:case 8:g.zt(this.element,"ytp-caption-window-bottom")}},Uks=function(a,x){var y="vertical-rl";
a.T.Ql===1&&(y="vertical-lr");g.LG&&(y=y==="vertical-lr"?"tb-lr":"tb-rl");g.F7(x,"-o-writing-mode",y);g.F7(x,"-webkit-writing-mode",y);g.F7(x,"writing-mode",y);g.F7(x,"text-orientation","upright");g.zt(x,"ytp-vertical-caption");a.B.params.GM===3&&(g.F7(x,"text-orientation",""),g.F7(x,"transform","rotate(180deg)"))},Y$P=function(a){var x=1+.25*(a.fontSizeIncrement||0);
if(a.offset===0||a.offset===2)x*=.8;return x},H0t=function(a,x){var y={},D=x.background?x.background:a.T.q0.background;
if(x.backgroundOpacity!=null||x.background){var M=x.backgroundOpacity!=null?x.backgroundOpacity:a.T.q0.backgroundOpacity;D=lzL(D);y.background="rgba("+D[0]+","+D[1]+","+D[2]+","+M+")";a.O6&&(y["box-decoration-break"]="clone",y["border-radius"]=a.Gt/8+"px")}if(x.fontSizeIncrement!=null||x.offset!=null)y["font-size"]=a.Cc*Y$P(x)+"px";D=1;M=x.color||a.T.q0.color;if(x.color||x.textOpacity!=null)M=lzL(M),D=x.textOpacity==null?a.T.q0.textOpacity:x.textOpacity,M="rgba("+M[0]+","+M[1]+","+M[2]+","+D+")",
y.color=M,y.fill=M;var N=x.charEdgeStyle;N===0&&(N=void 0);if(N){M="rgba(34, 34, 34, "+D+")";var F="rgba(204, 204, 204, "+D+")";x.Rm&&(F=M=x.Rm);var c=a.Cc/16/2,J=Math.max(c,1),G=Math.max(2*c,1),Q=Math.max(3*c,1),S=Math.max(5*c,1);D=[];switch(N){case 4:for(;Q<=S;Q+=c)D.push(G+"px "+G+"px "+Q+"px "+M);break;case 1:G=window.devicePixelRatio>=2?.5:1;for(N=J;N<=Q;N+=G)D.push(N+"px "+N+"px "+M);break;case 2:D.push(J+"px "+J+"px "+F);D.push("-"+J+"px -"+J+"px "+M);break;case 3:for(Q=0;Q<5;Q++)D.push("0 0 "+
G+"px "+M)}y["text-shadow"]=D.join(", ")}M="";switch(x.fontFamily){case 1:M='"Courier New", Courier, "Nimbus Mono L", "Cutive Mono", monospace';break;case 2:M='"Times New Roman", Times, Georgia, Cambria, "PT Serif Caption", serif';break;case 3:M='"Deja Vu Sans Mono", "Lucida Console", Monaco, Consolas, "PT Mono", monospace';break;case 5:M='"Comic Sans MS", Impact, Handlee, fantasy';break;case 6:M='"Monotype Corsiva", "URW Chancery L", "Apple Chancery", "Dancing Script", cursive';break;case 7:M=g.bj()?
'"Carrois Gothic SC", sans-serif-smallcaps':'Arial, Helvetica, Verdana, "Marcellus SC", sans-serif';break;case 0:case 4:M='"YouTube Noto", Roboto, Arial, Helvetica, Verdana, "PT Sans Caption", sans-serif'}M&&(y["font-family"]=M);M=x.offset;M==null&&(M=a.T.q0.offset);switch(M){case 0:y["vertical-align"]="sub";break;case 2:y["vertical-align"]="super"}x.fontFamily===7&&(y["font-variant"]="small-caps");x.bold&&(y["font-weight"]="bold");x.italic&&(y["font-style"]="italic");x.underline&&(y["text-decoration"]=
"underline");x.rPR&&(y.visibility="hidden");x.Dp===1&&a.J&&(y["text-combine-upright"]="all",y["text-orientation"]="mixed",M=g.Mc||g.wo,a.B.params.GM===3?y.transform=M?"rotate(90deg)":"rotate(180deg)":M&&(y.transform="rotate(-90deg)"));if(x.textEmphasis===1||x.textEmphasis===2||x.textEmphasis===3||x.textEmphasis===4||x.textEmphasis===5)if(g.Mc)y["font-weight"]="bold";else switch(y["text-emphasis-style"]="filled circle",y["text-emphasis-color"]="currentcolor",y["webkit-text-emphasis"]="filled circle",
x.textEmphasis){case 4:case 3:y["text-emphasis-position"]="under left";y["webkit-text-emphasis-position"]="under left";break;case 5:case 2:y["text-emphasis-position"]="over right",y["webkit-text-emphasis-position"]="over right"}return y},S7=function(a){a=a.split("px");
return a.length>0?(a=Number(a[0]))?a:0:0},i0L=function(a){a.Y=g.WK("SPAN");
g.F7(a.Y,{display:"block"});g.zt(a.Y,"caption-visual-line");a.U.appendChild(a.Y)},O0t=function(a,x){var y=g.WK("SPAN");
g.F7(y,{display:"inline-block","white-space":"pre-wrap"});g.F7(y,H0t(a,x));y.classList.add("ytp-caption-segment");a.Y.appendChild(y);y.previousElementSibling&&(g.F7(y.previousElementSibling,{"border-top-right-radius":"0","border-bottom-right-radius":"0"}),g.F7(y,{"border-top-left-radius":"0","border-bottom-left-radius":"0"}));return y},Vqh=function(a,x,y){a.UJ=a.UJ||!!y;
var D={};Object.assign(D,a.T.q0);Object.assign(D,y||x.T);Object.assign(D,a.n1.q0);(y=!a.Y)&&i0L(a);for(var M=a.yP&&a.N1&&g.fh(D,a.N1)?a.yP:O0t(a,D),N=typeof x.text==="string",F=N?x.text.split("\n"):[x.text],c=0;c<F.length;c++){var J=c>0||!x.append,G=F[c];J&&!y?(i0L(a),M=O0t(a,D)):J&&y&&(y=!1);G&&(M.appendChild(N?g.s$(G):G),N||G.tagName!=="RUBY"||G.childElementCount!==4||g.Mc||!g.cc(G.children[2],"text-emphasis")||(J=a.J?"padding-right":"padding-top",g.cc(G.children[2],"text-emphasis-position")&&(J=
a.J?"padding-left":"padding-bottom"),g.lH?g.F7(M,J,"1em"):g.F7(M,J,"0.5em")))}a.N1=D;a.yP=M;a.D.push(x)},Rmn=function(a,x,y,D){var M=x/360*16;
x>=a&&(a=640,D>y*1.3&&(a=480),M=y/a*16);return M},tq7=function(){this.J=this.time=this.mode=this.B=0;
this.U=new riL(this);this.N=new riL(this);this.T=[];this.clear()},b0F=function(a,x,y){if(a===255&&x===255||!a&&!x)return{vL:a,
K4:x,result:0};a=XKy[a];x=XKy[x];if(a&128){var D;if(D=!(x&128))D=x,D=y.hC()&&y.K4===D;if(D)return{vL:a,K4:x,result:1}}else if(x&128&&1<=a&&a<=31)return{vL:a,K4:x,result:2};return{vL:a,K4:x,result:3}},IzL=function(a,x,y,D){x===255&&y===255||!x&&!y?(++a.J===45&&a.reset(),a.U.B.clear(),a.N.B.clear()):(a.J=0,pKs(a.U,x,y,D))},emp=function(a,x){a.T.sort(function(M,N){var F=M.time-N.time;
return F===0?M.order-N.order:F});
for(var y=g.W(a.T),D=y.next();!D.done;D=y.next())D=D.value,a.time=D.time,D.type===0?IzL(a,D.Op,D.x3,x):D.type===1&&a.B&496&&pKs(a.N,D.Op,D.x3,x);a.T.length=0},K5=function(){this.type=0},L5=function(){this.state=this.K4=this.vL=0},adD=function(){this.timestamp=this.T=0},wS=function(a){this.N=a;
this.J=[];this.T=this.B=this.row=0;this.style=new K5;for(a=this.U=0;a<=15;a++){this.J[a]=[];for(var x=0;x<=32;x++)this.J[a][x]=new adD}},C5=function(a,x){if(a.style.type===3){for(var y=0,D=0,M=a.N.time+0,N="",F="",c=M,J=1;J<=15;++J){for(var G=!1,Q=D?D:1;Q<=32;++Q){var S=a.J[J][Q];
if(S.T!==0){y===0&&(y=J,D=Q);G=String.fromCharCode(S.T);var K=S.timestamp;K<M&&(M=K);S.timestamp=c;F&&(N+=F,F="");N+=G;G=!0}if((S.T===0||Q===32)&&G){F="\n";break}else if(D&&!G)break}if(y&&!G)break}N&&x.U(y,D,M,c,N)}else for(D=y=0,N=M=a.N.time+0,F=1;F<=15;++F)for(c="",J=1;J<=32;++J)if(Q=a.J[F][J],S=Q.T,S!==0&&(y===0&&(y=F,D=J),G=String.fromCharCode(S),K=Q.timestamp,K<=M&&(M=K),c+=G,Q.reset()),J===32||S===0)c&&x.U(y,D,M,N,c),M=N,c="",D=y=0},MIF=function(a,x){switch(a){case 0:return xFF[(x&127)-32];
case 1:return y3s[x&15];case 2:return j_V[x&31];case 3:return DFF[x&31]}return 0},qv=function(a){return a.J[a.row][a.B]},dS=function(a,x,y){x>=2&&a.B>1&&(--a.B,qv(a).T=0);
var D=qv(a);D.timestamp=a.N.time+0;D.T=MIF(x,y);a.B<32&&a.B++},NUV=function(a,x,y,D){for(var M=0;M<D;M++)for(var N=0;N<=32;N++){var F=a.J[x+M][N],c=a.J[y+M][N];
F.T=c.T;F.timestamp=c.timestamp}},Zv=function(a,x,y){for(var D=0;D<y;D++)for(var M=0;M<=32;M++)a.J[x+D][M].reset()},FGF=function(a){a.row=a.T>0?a.T:1;
a.B=1;Zv(a,0,15)},zIY=function(a){this.J=a;
this.N=0;this.style=new K5;this.D=new wS(this.J);this.Y=new wS(this.J);this.text=new wS(this.J);this.B=this.D;this.U=this.Y;this.T=this.B},c3h=function(a,x,y){var D=a.B,M=!1;
switch(a.style.get()){case 4:case 1:case 2:a.style.get()===4&&D.T>0||(C5(D,y),FGF(a.B),FGF(a.U),D.row=15,D.T=x,M=!0)}a.style.set(3);a.T=D;a.T.style=a.style;a.J.mode=1<<D.U;M?D.B=1:D.T!==x&&(D.T>x?(C5(D,y),Zv(D,D.row-D.T,x)):D.row<x&&(x=D.T),D.T=x)},o8F=function(a){a.style.set(1);
a.T=a.U;a.T.T=0;a.T.style=a.style;a.J.mode=1<<a.T.U},J3t=function(a){a.style.set(4);
a.T=a.text;a.T.style=a.style;a.J.mode=1<<a.T.U},riL=function(a){this.T=a;
this.N=0;this.J=new zIY(this.T);this.D=new zIY(this.T);this.B=new L5;this.U=this.J},pKs=function(a,x,y,D){a.B.update();
x=b0F(x,y,a.B);switch(x.result){case 0:return;case 1:case 2:return}var M=x.vL;y=x.K4;if(32<=M||!M)a.T.mode&a.T.B&&(x=M,x&128&&(x=127),y&128&&(y=127),a=a.U.T,x&96&&dS(a,0,x),y&96&&dS(a,0,y),x!==0&&y!==0&&a.style.type===3&&C5(a,D));else if(M&16)a:if(!a.B.matches(M,y)&&(x=a.B,x.vL=M,x.K4=y,x.state=2,x=M&8?a.D:a.J,a.U=x,a.T.mode=1<<(a.N<<2)+(x.N<<1)+(x.style.type===4?1:0),(a.T.mode|1<<(a.N<<2)+(x.N<<1)+(x.style.type!==4?1:0))&a.T.B))if(y&64){D=[11,11,1,2,3,4,12,13,14,15,5,6,7,8,9,10][(M&7)<<1|y>>5&1];
a=y&16?((y&14)>>1)*4:0;y=x.T;switch(x.style.get()){case 4:D=y.row;break;case 3:if(D!==y.row){if(D<y.T&&(D=y.T,D===y.row))break;var N=1+y.row-y.T,F=1+D-y.T;NUV(y,F,N,y.T);x=N;M=y.T;F<N?(N=F+M-N,N>0&&(x+=N,M-=N)):(N=N+M-F,N>0&&(M-=N));Zv(y,x,M)}}y.row=D;y.B=a+1}else switch(M&7){case 1:switch(y&112){case 32:dS(x.T,0,32);break a;case 48:y===57?(D=x.T,qv(D).T=0,D.B<32&&D.B++):dS(x.T,1,y&15)}break;case 2:y&32&&dS(x.T,2,y&31);break;case 3:y&32&&dS(x.T,3,y&31);break;case 4:case 5:if(32<=y&&y<=47)switch(y){case 32:o8F(x);
break;case 33:D=x.T;D.B>1&&(--D.B,qv(D).T=0);break;case 36:D=x.T;x=qv(D);for(a=0;a<=15;a++)for(y=0;y<=32;y++)if(D.J[a][y]===x){for(;y<=32;y++)D.J[a][y].reset();break}break;case 37:c3h(x,2,D);break;case 38:c3h(x,3,D);break;case 39:c3h(x,4,D);break;case 40:dS(x.T,0,32);break;case 41:x.style.set(2);x.T=x.B;x.T.T=0;x.T.style=x.style;x.J.mode=1<<x.T.U;break;case 42:D=x.text;D.T=15;D.style.set(4);FGF(D);J3t(x);break;case 43:J3t(x);break;case 44:a=x.B;switch(x.style.get()){case 1:case 2:case 3:C5(a,D)}Zv(a,
0,15);break;case 45:b:{a=x.T;switch(x.style.get()){default:case 2:case 1:break b;case 4:if(a.row<15){++a.row;a.B=1;break b}break;case 3:}a.T<2&&(a.T=2,a.row<a.T&&(a.row=a.T));x=a.row-a.T+1;C5(a,D);NUV(a,x,x+1,a.T-1);Zv(a,a.row,1)}break;case 46:Zv(x.U,0,15);break;case 47:C5(x.B,D),x.U.updateTime(x.J.time+0),D=x.U,x.U=x.B,x.B=D,o8F(x)}break;case 7:switch(y){case 33:case 34:case 35:D=x.T,(D.B+=y&3)>32&&(D.B=32)}}},GXV=function(){},n5=function(a,x,y,D,M,N,F){N=N===void 0?!1:N;
F=F===void 0?null:F;g.gr.call(this,a,a+x,{priority:y,namespace:"captions"});this.windowId=D;this.text=M;this.append=N;this.T=F},Sk7=function(a,x,y,D,M,N,F){var c=N[0],J=F[c.getAttribute("p")];
if(J.P3===1){var G=N[1],Q=N[2];N=N[3];c.getAttribute("t");G.getAttribute("t");Q.getAttribute("t");N.getAttribute("t");c.getAttribute("p");G.getAttribute("p");N.getAttribute("p");F=F[Q.getAttribute("p")];c=Q_D(c.textContent,G.textContent,Q.textContent,N.textContent,F);return new n5(a,x,M,y,c,D,J)}switch(J.P3){case 9:case 10:J.textEmphasis=1;break;case 11:J.textEmphasis=2;break;case 12:J.textEmphasis=3;break;case 13:J.textEmphasis=4;break;case 14:J.textEmphasis=5}return new n5(a,x,M,y,c.textContent||
"",D,J)},Q_D=function(a,x,y,D,M){var N=g.bj(),F=N?g.WK("DIV"):g.WK("RUBY"),c=g.WK("SPAN");
c.textContent=a;F.appendChild(c);a=N?g.WK("DIV"):g.WK("RP");a.textContent=x;F.appendChild(a);x=N?g.WK("DIV"):g.WK("RT");x.textContent=y;F.appendChild(x);y=M.P3;if(y===10||y===11||y===12||y===13||y===14)if(g.F7(x,"text-emphasis-style","filled circle"),g.F7(x,"text-emphasis-color","currentcolor"),g.F7(x,"webkit-text-emphasis","filled circle"),M.P3===11||M.P3===13)g.F7(x,"webkit-text-emphasis-position","under left"),g.F7(x,"text-emphasis-position","under left");y=!0;if(M.P3===4||M.P3===7||M.P3===12||
M.P3===14)g.F7(F,"ruby-position","over"),g.F7(F,"-webkit-ruby-position","before");else if(M.P3===5||M.P3===6||M.P3===11||M.P3===13)g.F7(F,"ruby-position","under"),g.F7(F,"-webkit-ruby-position","after"),y=!1;M=N?g.WK("DIV"):g.WK("RP");M.textContent=D;F.appendChild(M);N&&(D=y,g.F7(F,{display:"inline-block",position:"relative"}),N=F.firstElementChild.nextElementSibling,g.F7(N,"display","none"),N=N.nextElementSibling,g.F7(N,{"font-size":"0.5em","line-height":"1.2em","text-align":"center",position:"absolute",
left:"50%",transform:"translateX(-50%)",width:"400%"}),g.F7(F.lastElementChild,"display","none"),D?(g.F7(F,"padding-top","0.6em"),g.F7(N,"top","0")):(g.F7(F,"padding-bottom","0.6em"),g.F7(N,"bottom","0")));return F},vQ=function(){g.A.apply(this,arguments)},PQ=function(a,x,y,D,M){g.gr.call(this,a,a+x,{priority:y,
namespace:"captions"});this.id=D;this.params=M;this.T=[]},KG7=function(a){var x="_"+TB++;
return new PQ(0,0x8000000000000,0,x,a)},lZ=function(a){vQ.call(this);
this.U=a;this.pens={};this.V={};this.BJ={};this.N="_"+TB++;this.Y={};this.B=this.T=null;this.D=!0},kP=function(a,x){a=a.getAttribute(x);
if(a!=null)return Number(a)},uZ=function(a,x){a=a.getAttribute(x);
if(a!=null)return a==="1"},m1=function(a,x){a=kP(a,x);
return a!==void 0?a:null},EZ=function(a,x){a=a.getAttribute(x);
if(a!=null)return WQ.test(a),a},LGD=function(a,x){var y={},D=x.getAttribute("ws");
Object.assign(y,D?a.BJ[D]:a.U);a=m1(x,"mh");a!=null&&(y.a6=a);a=m1(x,"ju");a!=null&&(y.textAlign=a);a=m1(x,"pd");a!=null&&(y.GM=a);a=m1(x,"sd");a!=null&&(y.Ql=a);a=EZ(x,"wfc");a!=null&&(y.windowColor=a);x=kP(x,"wfo");x!==void 0&&(y.windowOpacity=x/255);return y},wcP=function(a,x){var y={},D=x.getAttribute("wp");
D&&Object.assign(y,a.V[D]);a=m1(x,"ap");a!=null&&(y.uM=a);a=kP(x,"cc");a!=null&&(y.AS=a);a=kP(x,"ah");a!=null&&(y.bb=a);a=kP(x,"rc");a!=null&&(y.n4=a);x=kP(x,"av");x!=null&&(y.VM=x);return y},C2D=function(a,x,y,D){var M={};
Object.assign(M,wcP(a,x));Object.assign(M,LGD(a,x));D?g.fh(M,a.U)?(D=a.N,M=a.U):D="_"+TB++:D=x.getAttribute("id")||"_"+TB++;a=kP(x,"t")+y;x=kP(x,"d")||0x8000000000000;if(M.GM===2||M.GM===3)y=M.n4,M.n4=M.AS,M.AS=y;return new PQ(a,x,0,D,M)},sZ=function(a){vQ.call(this);
this.D=a;this.T=new Map;this.U=new Map;this.N=new Map;this.B=new Map},BQ=function(a){a=g.Dz(Math.round(a),0,16777215).toString(16).toUpperCase();
return"#000000".substring(0,7-a.length)+a},qks=function(a,x,y,D,M){D===0&&(D=0x8000000000000);
var N={};x.wpWinPosId&&Object.assign(N,a.U.get(x.wpWinPosId));x.wsWinStyleId&&Object.assign(N,a.N.get(x.wsWinStyleId));a=x.rcRowCount;a!==void 0&&(N.n4=a);x=x.ccColCount;x!==void 0&&(N.AS=x);if(N.GM===2||N.GM===3)x=N.n4,N.n4=N.AS,N.AS=x;return new PQ(y,D,0,M,N)},hp=function(a,x,y){g.Cf.call(this,a);
this.videoData=x;this.audioTrack=y;this.N=x.Oc},$P=function(a,x,y,D,M,N,F,c,J,G){Q7.call(this,a,x,y,D,M,N,F,c,J,G);
this.type=1},f5=function(a,x,y){this.trackData=a;
this.D=y;this.version=this.N=this.J=this.byteOffset=0;this.B=[];this.T=new DataView(this.trackData)},gS=function(a){var x=a.byteOffset;
a.byteOffset+=1;return a.T.getUint8(x)},RT=function(a){var x=a.byteOffset;
a.byteOffset+=4;return a.T.getUint32(x)},YP=function(a,x){vQ.call(this);
this.B=a;this.U=x;this.track=this.U.languageName==="CC3"?4:0;this.T=new tq7;this.T.B=1<<this.track},ZeG=function(a){if(typeof a==="string")return!1;
a=new f5(a,8,0);return dFn(a)},dFn=function(a){if(!(a.byteOffset<a.T.byteLength)||RT(a)!==1380139777)return!1;
a.version=gS(a);if(a.version>1)return!1;gS(a);gS(a);gS(a);return!0},Ap=function(a,x,y,D,M,N,F,c,J,G){Q7.call(this,a,x,y,D,M,N,F,c,J,G);
var Q=this;this.type=2;this.tP=[];this.cJ=this.V=this.e8=0;this.OJ=NaN;this.Af=0;this.bO=null;this.tf=new g.Id(this.Hg,433,this);this.N&&(G.createClientVe(this.N,this,167342),this.Z(this.N,"click",function(){G.logClick(Q.N)}),a=new g.WR(this.element,!0),g.U(this,a),a.subscribe("hoverstart",function(){G.logVisibility(Q.N,!0)},this));
g.zt(this.element,"ytp-caption-window-rollup");g.U(this,this.tf);g.F7(this.element,"overflow","hidden")},n8y=function(a,x){if(!x)return"";
a.J&&a.B.params.Ql!==1&&(x*=-1);return"translate"+(a.J?"X":"Y")+"("+x+"px)"},v8J=function(a){a.tP=Array.from(a.element.getElementsByClassName("caption-visual-line"));
for(var x=a.B.params.n4,y=0,D=0,M=a.tP.length-1;y<x&&M>-1;){var N=a.tP[M];D+=a.J?N.offsetWidth:N.offsetHeight;y++;M--}a.V=D;x=Math;y=x.max;isNaN(a.OJ)&&((D=a.T.AS)?(M=g.WK("SPAN"),g.RZ(M,"\u2013".repeat(D)),g.F7(M,H0t(a,a.T.q0)),a.U.appendChild(M),a.OJ=M.offsetWidth,a.U.removeChild(M)):a.OJ=0);D=a.U;a.cJ=y.call(x,a.OJ,a.Af,(a.J?D.offsetHeight:D.offsetWidth)+1)},P27=function(a,x){v8J(a);
var y=a.tP.reduce(function(N,F){return(a.J?F.offsetWidth:F.offsetHeight)+N},0);
y=a.V-y;if(y!==a.e8){var D=y>0&&a.e8===0,M=y<a.e8;x||isNaN(y)||D||!M||(g.zt(a.element,"ytp-rollup-mode"),a.Z(a.element,"transitionend",a.Hg));g.F7(a.U,"transform",n8y(a,y));a.e8=y}v8J(a)},TUV=function(a,x,y,D){var M=this;
this.L=a;this.J=x;this.logger=y;this.w0=D;this.dF=[];this.WI=[];this.T=null;this.uO={b6J:function(){return M.T},
ws:function(){return M.dF}};
a=g.ts(this.L.j().experiments,"html5_override_micro_discontinuities_threshold_ms");this.B=a>0?a:10},kXJ=function(a,x){a.T=function(y,D){if(y.info.J){var M=y;
if(a.WI.length>0){for(M=a.WI.shift();a.WI.length>0;)M=g.qO(M,a.WI.shift());M=g.qO(M,y)}if(M){y=M;try{var N=g.dt(y)*1E3}catch(G){N=y.info.startTime*1E3}try{var F=g.aY1(y)*1E3}catch(G){F=y.info.duration*1E3}if(N<0||F<0)N<0&&(N=y.info.startTime*1E3),F<0&&(F=y.info.duration*1E3);y.info.startTime=N/1E3;y.info.U=N/1E3;y.info.duration=F/1E3;y.info.Y=F/1E3;N=a.cB(M);F=N.bY;N={formatId:N.formatId,startTimeMs:N.startTimeMs,durationMs:N.durationMs,QX:F,jY:F};F=ldL(a.dF,N.startTimeMs);var c=(y=F>=0?a.dF[F]:null)?
y.startTimeMs+y.durationMs:0,J=N.startTimeMs+N.durationMs;!y||N.startTimeMs-c>a.B?a.dF.splice(F+1,0,N):(y.durationMs=Math.max(c,J)-y.startTimeMs,y.jY=Math.max(y.jY,N.jY));D(a.dF);N=g.Cc(M);D=a.J;N=N.buffer.slice(N.byteOffset,N.byteLength+N.byteOffset);M=M.info.U;D.D?D.U==null?g.Lc(D.logger,350058965,"Null loaded track meta data at captions data received"):x.eh(N,D.U,M*1E3):g.Lc(D.logger,350058965,"Null Representation at captions data received")}else g.Lc(a.logger,350058965,"Empty slice")}else a.WI.push(y)};
a.L.addEventListener("sabrCaptionsDataLoaded",a.T)},ldL=function(a,x){a=g.SS(a,{startTimeMs:x},function(y,D){return y.startTimeMs-D.startTimeMs});
return a>=0?a:-a-2},UZ=function(a,x){g.Cf.call(this,x);
this.B=a;this.L=x;this.logger=new g.Kc("caps");this.U=this.D=null;this.Y=new TUV(this.L,this,this.logger,this.B.w0)},u77=function(a,x){var y=[],D;
for(D in a.B.T)if(a.B.T.hasOwnProperty(D)){var M=a.B.T[D];if(g.dE(M,x||null)){var N=M.info.id,F=N,c="."+N,J="",G="";if(M=M.info.captionTrack)N=M.languageCode,F=M.displayName,c=M.vssId,J=M.kind,G=M.id;y.push(new g.qc({id:D,languageCode:N,languageName:F,is_servable:!0,is_default:!0,is_translateable:!1,vss_id:c,kind:J,captionId:G}))}}return y},mFs=function(a,x,y){var D=[],M;
for(M in a.B.T)if(a.B.T.hasOwnProperty(M)){var N=a.B.T[M];if(g.dE(N,y||null)){var F=N.info.captionTrack;F&&F.languageCode===x&&D.push(N)}}return D.length?D[0]:null},WGt=function(a,x){if(!g.Pks(a)||a.T!=null&&g.wRG(x,a.T)&&a.T.T.rawcc!=null)return!1;
x=!!a.T&&a.T.isManifestless&&Object.values(a.T.T).some(function(y){return g.dE(y,"386")});
a=!!a.T&&!a.T.isManifestless&&g.QJT(a.T);return x||a},E8L=function(){vQ.call(this)},BUs=function(a){var x=s_y.length;
if(a.byteLength<x)return!1;a=new Uint8Array(a,0,x);for(var y=0;y<x;y++)if(s_y[y]!==a[y])return!1;return!0},hIF=function(a,x,y,D,M,N,F,c,J){switch(F.tagName){case "b":c.bold=!0;
break;case "i":c.italic=!0;break;case "u":c.underline=!0}for(var G=0;G<F.childNodes.length;G++){var Q=F.childNodes[G];if(Q.nodeType===3)Q=new n5(x,y,D,M.id,Q.nodeValue,N||G>0,g.sJ(c)?void 0:c),J.push(Q),M.T.push(Q);else{var S={};Object.assign(S,c);hIF(a,x,y,D,M,!0,Q,S,J)}}},$Fy=function(a){var x=a.split(":");
a=0;x=g.W(x);for(var y=x.next();!y.done;y=x.next())a=a*60+Number(y.value);return a*1E3},fdL=function(a,x,y,D){D=Object.assign({a6:0},D);
return new PQ(a,x,y,"_"+TB++,D)},HQ=function(a,x){g.A.call(this);
this.L=a;this.S=x;this.T=null;this.B=this.L.f5();this.logger=new g.Kc("caps")},RIh=function(a,x,y){if(typeof x==="string"||ZeG(x))return[{trackData:x,
Sf:y}];if(typeof x==="string"&&x.substring(0,6)==="WEBVTT"||typeof x!=="string"&&BUs(x))return[{trackData:x,Sf:y}];var D=new DataView(x);if(D.byteLength<=8||D.getUint32(4)!==1718909296)return[];var M=g.xjq(D);if(a.B&&M){var N=g.r97(M),F=g.t16(M);M=M.w6;N&&M&&a.B.oT(M,N,F)}a=g.Ln(D,1835295092);if(!a||!a.length||!a[0].size)return[];N=[];for(F=0;F<a.length;F++)M=a[F],M=new Uint8Array(x,M.dataOffset,M.size-(M.dataOffset-M.offset)),M=g.Cm(M),N.push({trackData:M,Sf:y+F*1E3});g8V(D,N,y);return N=N.filter(function(c){return!!c.trackData})},
g8V=function(a,x,y){var D=g.F8(a,0,1836476516),M=9E4;
D&&(M=g.zn(D)||9E4);D=0;for(var N=g.Ln(a,1836019558),F=0;F<N.length;F++){var c=N[F];F<x.length&&(c=g.F8(a,c.dataOffset,1953653094))&&(c=g.F8(a,c.dataOffset,1952867444))&&(c=g.S3(c)/M*1E3,F===0&&(D=c),x[F].Sf=c-D+y||y*F*1E3)}},Ykp=function(a,x,y){a.T||(a.T=new E8L);
a=a.T.J(x,y);Math.random()<.01&&g.E0(Error("Deprecated subtitles format in web player: WebVTT"));return a},A3n=function(a){var x={};
if(a=g.nO(a))x.lang=a,g.kUS.test(a)&&(x.GM=1);return x},ieY=function(a){g.Lf.call(this,a);
var x=this;this.L=a;this.yP=[];this.tP={};this.Gt={};this.V=!1;this.J="NONE";this.B=this.BJ=this.cJ=this.Cc=this.zt=null;this.Af={mu:function(){x.mu()},
eh:function(N,F,c,J){x.eh(N,F,c,J)}};
this.T=null;this.S=this.L.j();this.videoData=this.L.getVideoData();this.S8=this.L.q1();this.N={q0:{}};this.D={q0:{}};g.aQ(this.videoData)?this.J="OFFLINE":g.LH8(this.videoData,this.L)?this.J="HLS":WGt(this.videoData,this.L)?this.J="SABR_LIVE":g.CnC(this.videoData,this.L)?this.J="LIVE":this.videoData.captionTracks.length?this.J="INNERTUBE":this.videoData.O6&&(this.J="TTS");this.YG=this.S.controlsType==="3";this.EJ=new HQ(this.L,this.S);this.OJ=new g.zW(this);this.Y=new g.O({W:"div",G:"ytp-caption-window-container",
X:{id:"ytp-caption-window-container"}});this.dS={top:0,right:0,bottom:0,left:0,width:1,height:1};var y=null,D=g.R9("yt-html5-player-modules::subtitlesModuleData");D&&(y=new g.mv(D));this.storage=y;var M;this.iY=!((M=a.vN())==null||!M.j5());this.U=UFh(this);this.UJ=!this.U&&this.YG&&this.iY&&(this.J==="LIVE"||this.J==="SABR_LIVE");g.U(this,this.EJ);this.U?this.e8=this.N1=null:(this.N1=new g.pZ(this.sN,void 0,this),g.U(this,this.N1),this.e8=new g.Id(this.S9t,2E3,this),g.U(this,this.e8));g.U(this,this.OJ);
g.f1(this.player,this.Y.element,4);g.U(this,this.Y);this.U||this.OJ.Z(a,"resize",this.oo);(this.tf=g.Rb(this.S)&&!g.nI()&&!this.L.isFullscreen()&&!this.U&&!this.UJ)&&this.OJ.Z(a,"resize",this.i1P);this.OJ.Z(a,"onPlaybackAudioChange",this.mGJ);this.OJ.Z(a,g.Y6("captions"),function(N){x.onCueRangeEnter(N)});
this.OJ.Z(a,g.A9("captions"),function(N){x.onCueRangeExit(N)});
HeV(this,uzF()||{});this.player.Bm("onCaptionsModuleAvailable");this.J==="HLS"&&this.U&&(a=this.L.vN().Qn(),this.iY&&this.OJ.Z(a.textTracks,"addtrack",this.Ht8))},r3J=function(a){if(a.S.Pl===1||a.videoData.tU===1||g.WC(a.videoData,"yt:cc")==="alwayson")return!0;
if(a.videoData.captionTracks.length)var x=a.getAudioTrack().B;if(a.S.Pl===2){if(g.xY(a.S))var y=OeY(a);else if(a.storage)try{y=a.storage.get("module-enabled")}catch(M){a.storage.remove("module-enabled")}else y=null;if(y!=null)return!!y}y=q$y(a.player.getAudioTrack(),g.xY(a.S));var D=g.WC(a.videoData,"yt:cc");if(VIn(a)===void 0){if(y==="CAPTIONS_INITIAL_STATE_ON_RECOMMENDED")return D?D==="on":!0;if(y==="CAPTIONS_INITIAL_STATE_OFF_RECOMMENDED")return D==="on"}else return D==="on";return x==="ON"||g.WC(a.videoData,
"yt:cc")==="on"},iZ=function(a,x){if(a.T&&(x===void 0||!x)||!a.videoData.captionTracks.length)return!1;
a=a.getAudioTrack();return!!a.T||a.B==="FORCED_ON"},VIn=function(a){var x=void 0,y=g.i8().WG(65);
if(g.xY(a.S)&&y!=null){if(OeY(a)!=null)return!1;x=!y}return x},V7=function(a,x){if(!a.B)return null;
if(a.BJ&&a.BJ.U)return a.BJ.U;x=tI7(a,x);x=g.bn(a.B.T,x);var y=null;if(dk7(a.S)){var D=a.L.isInline()?void 0:g.gX("yt-player-caption-sticky-language");for(var M=[D,a.videoData.captionsLanguagePreference,a.S.captionsLanguagePreference,g.WC(a.videoData,"yt:cc_default_lang")],N=!1,F=0;F<M.length;F++){var c=M[F];if(c){N=!0;for(var J=0;J<x.length;J++)if(g.nO(x[J])===c)return x[J];for(J=0;J<x.length;J++)if(g.nO(x[J]).split("-")[0]===c.split("-")[0])return x[J]}}if(N&&a.B&&(M=a.B.N,M.length))for(M=g.W(M),
N=M.next();!N.done;N=M.next())if(N=N.value,N.languageCode===D){y=N;break}}else for(D=[a.videoData.captionsLanguagePreference,a.S.captionsLanguagePreference,g.WC(a.videoData,"yt:cc_default_lang")],M=0;M<D.length;M++)for(N=0;N<x.length;N++)if(g.nO(x[N])===D[M])return x[N];D=null;a.BJ&&a.BJ.J&&(D=a.BJ.J);D||(D=x.find(function(G){return G.isDefault})||null);
D||(D=x[0]||OZ(a));D&&y&&g.nO(D).split("-")[0]!==y.languageCode.split("-")[0]&&(D=Z0G(D,y));return D},OZ=function(a){return a.BJ&&a.BJ.T},rS=function(a){var x=OZ(a);
return!!x&&a.T===x},Xch=function(a,x){if(a.T){var y=a.L.vN().Qn().textTracks,D=null;
a.J==="HLS"?D=a.T.getId():D=a.T.toString();for(a=0;a<y.length;a++){var M=y[a];M.id===D&&(x?M.mode!=="showing"&&(M.mode="showing"):M.mode==="showing"&&(M.mode="disabled"))}}},bZ=function(a,x,y){a.loaded&&a.unload();
y!=null&&(a.V=y,a.V&&(g.xY(a.S)?tp(a,!!x):Xg(a,!!x)));x!==null||iZ(a,!0)||a.G$(x,!!x,a.V?"m":"s");a.T=x;iZ(a)&&(a.T=OZ(a));var D;bes(a,(D=a.T)!=null?D:void 0);a.load()},Idy=function(a,x){if(x instanceof PQ){var y=a.tP[x.id];
y&&y.B!==x&&(y.dispose(),delete a.tP[x.id],y=null);y||(y=pcs(a,x))&&(a.tP[x.id]=y)}else y=x.windowId,a.Gt[y]||(a.Gt[y]=[]),a.Gt[y].push(x)},pcs=function(a,x){var y=eI7(a);
if(!y)return null;var D=a.T?g.nO(a.T):null;D&&g.kUS.test(D)&&(x.params.GM=1);var M=a.S8.getPlayerSize();D=M.height*a.dS.height;M=M.width*a.dS.width;a.S.playerStyle!=="google-live"||a.N.isDefault||Object.assign(x.params,a.N);switch(x.params.a6!=null?x.params.a6:x.T.length>1?1:0){case 1:return new $P(x,a.N,a.D,y.width,y.height,M,D,a.S.experiments,a.TR.bind(a),a.L);case 2:return new Ap(x,a.N,a.D,y.width,y.height,M,D,a.S.experiments,a.TR.bind(a),a.L);default:return new Q7(x,a.N,a.D,y.width,y.height,M,
D,a.S.experiments,a.TR.bind(a),a.L)}},HeV=function(a,x,y){y=y===void 0?!1:y;
var D=p5.q0;a.N={};Object.assign(a.N,p5);a.N.q0={};Object.assign(a.N.q0,D);a.D={q0:{}};var M=x.backgroundOverride?a.D:a.N,N=x.background||D.background;WQ.test(N);M.q0.background=N;M=x.colorOverride?a.D:a.N;N=x.color||D.color;WQ.test(N);M.q0.color=N;M=x.windowColorOverride?a.D:a.N;N=x.windowColor||p5.windowColor;WQ.test(N);M.windowColor=N;M=x.backgroundOpacityOverride?a.D:a.N;N=x.backgroundOpacity;N==null&&(N=D.backgroundOpacity);M.q0.backgroundOpacity=N;M=x.fontSizeIncrementOverride?a.D:a.N;N=x.fontSizeIncrement;
N==null&&(N=D.fontSizeIncrement);M.q0.fontSizeIncrement=N;N=x.fontStyleOverride?a.D:a.N;M=x.fontStyle;M==null&&(M=D.bold&&D.italic?3:D.bold?1:D.italic?2:0);N=N.q0;switch(M){case 1:N.bold=!0;delete N.italic;break;case 2:delete N.bold;N.italic=!0;break;case 3:N.bold=!0;N.italic=!0;break;default:delete N.bold,delete N.italic}M=x.textOpacityOverride?a.D:a.N;N=x.textOpacity;N==null&&(N=D.textOpacity);M.q0.textOpacity=N;M=x.windowOpacityOverride?a.D:a.N;N=x.windowOpacity;N==null&&(N=p5.windowOpacity);M.windowOpacity=
N;M=x.charEdgeStyleOverride?a.D:a.N;N=x.charEdgeStyle;N==null&&(N=D.charEdgeStyle);M.q0.charEdgeStyle=N;M=x.fontFamilyOverride?a.D:a.N;N=x.fontFamily;N==null&&(N=D.fontFamily);M.q0.fontFamily=N;a.loaded&&a.oo();y&&g.fI("yt-player-caption-display-settings",x,2592E3)},apF=function(a,x){if(!a.B)return{};
if(x){g.sJ(x)||a.YL(x.vss_id,"m");if(a.U&&a.J!=="HLS"||!g.BJ(x))return;if(g.sJ(x)){bZ(a,null,!0);return}for(var y,D=g.bn(a.B.T,!0),M=0;M<D.length;M++){var N=D[M];N.languageCode!==x.languageCode||y&&(N.languageName!==x.languageName||(N.captionId||"")!==(x.captionId||"")||g.dc(N)!==x.displayName)||(y=x.translationLanguage?Z0G(N,x.translationLanguage):N)}a.xg(x.position);!y||y===a.T&&a.loaded||(x=g.nu(),D=g.nO(y),x.length&&D===x[x.length-1]||(x.push(D),g.fI("yt-player-caption-language-preferences",x)),
dk7(a.S)&&!a.L.isInline()&&g.fI("yt-player-caption-sticky-language",D,2592E3),bZ(a,y,!0))}else return a.loaded&&a.T&&!rS(a)?g.ZV(a.T):{};return""},yHs=function(a,x,y){x&&!a.cJ?(x=KG7({GM:0,
lang:"ja"}),a.cJ=[x,new n5(x.start,x.end-x.start,0,x.id,y!=null?y:"\u5b57\u5e55\u306f\u6b21\u306e\u3088\u3046\u306b\u306a\u308a\u307e\u3059")],a.player.GF(a.cJ)):!x&&a.cJ&&(xZn(a,a.cJ),a.cJ=null)},xZn=function(a,x){a.player.qK(x);
x=g.W(x);for(var y=x.next();!y.done;y=x.next())g.Dk(a.yP,y.value);oT(a.N1)},bes=function(a,x){a.S.C("html5_modify_caption_vss_logging")&&(a.videoData.jq=x)},eI7=function(a){var x=a.S8.getVideoContentRect(!0).height,y=a.S8.getVideoContentRect(!0).width;
if(!x||!y)return null;x*=a.dS.height;y*=a.dS.width;return{width:y,height:x}},Xg=function(a,x){if(a.storage)try{a.storage.set("module-enabled",x)}catch(y){}},tp=function(a,x){a.L.isInline()||g.fI("yt-player-sticky-caption",x,2592E3)},OeY=function(a){if(!a.L.isInline())return g.gX("yt-player-sticky-caption")},UFh=function(a){var x,y=!((x=a.L.vN())==null||!x.gR());
return a.J==="HLS"&&y?!0:a.YG&&y&&a.J!=="LIVE"&&a.J!=="SABR_LIVE"},tI7=function(a,x){if(a.J==="HLS")return!1;
g.iU(a.videoData)&&(x=!0);x||(x=a.J==="TTS"?!1:a.J==="INNERTUBE"?!1:!0);return x||a.S.C("web_deprecate_always_includes_asr_setting")&&g.xY(a.S)?!0:!!g.i8().WG(66)};
g.pA.prototype.oT=g.YG(72,function(a,x,y){this.B.set(a,{dj:x,oL:y})});
g.Io.prototype.oT=g.YG(71,function(a,x,y){this.cJ.oT(a,x,y)});
g.Cf.prototype.Dh=g.YG(70,function(){return!1});
g.Cf.prototype.pH=g.YG(69,function(){});
g.qM.prototype.pH=g.YG(68,function(a,x,y){var D=this;this.hP();x=this.Rl(a,x);var M=this.R7.j().C("html5_report_captions_ctmp_qoe"),N=(0,g.lY)();this.g$();CHh(this,x,{format:"RAW",onSuccess:function(F){D.B=null;if(M){var c=(F.responseText.length/1024).toFixed(),J=(0,g.lY)();D.videoData.AP("capresp",{ms:J-N,kb:c})}y.eh(F.responseText,a)},
onError:M?function(F){var c;F=(c=F==null?void 0:F.status)!=null?c:0;D.videoData.AP("capfail",{status:F})}:void 0,
withCredentials:!0})});
g.ZI.prototype.pH=g.YG(67,function(a,x,y){var D=this;this.hP();x=this.Rl(a,x);this.g$();this.B=g.Wm(x,{format:"RAW",onSuccess:function(M){D.B=null;y.eh(M.responseText,a)},
withCredentials:!0})});
g.RI.prototype.B0=g.YG(66,function(){for(var a=g.vK(document,"track",void 0,this.T),x=0;x<a.length;x++)g.f0(a[x])});
g.mX.prototype.B0=g.YG(65,function(){for(var a=g.vK(document,"track",void 0,this.T),x=0;x<a.length;x++)g.f0(a[x])});
g.sR.prototype.B0=g.YG(64,function(){this.mediaElement.B0()});
g.RI.prototype.j5=g.YG(63,function(){return!(!this.T.textTracks||!this.T.textTracks.addEventListener)});
g.mX.prototype.j5=g.YG(62,function(){return!(!this.T.textTracks||!this.T.textTracks.addEventListener)});
g.sR.prototype.j5=g.YG(61,function(){return this.mediaElement.j5()});
g.RI.prototype.gR=g.YG(60,function(){return!!this.T.textTracks});
g.mX.prototype.gR=g.YG(59,function(){return!!this.T.textTracks});
g.sR.prototype.gR=g.YG(58,function(){return this.mediaElement.gR()});
g.RI.prototype.l6=g.YG(57,function(a){for(var x=0;x<a.length;x++)this.T.appendChild(a[x])});
g.mX.prototype.l6=g.YG(56,function(a){for(var x=0;x<a.length;x++)this.T.appendChild(a[x])});
g.sR.prototype.l6=g.YG(55,function(a){this.mediaElement.l6(a)});
g.uS.prototype.Fg=g.YG(43,function(a){var x=g.qu(this.app,{playerType:void 0});return x?x.Fg(a):!1});
g.Hi.prototype.Fg=g.YG(42,function(a){return this.Tt.gs.Fg(a)});
g.vS.prototype.Fg=g.YG(41,function(a){return this.yL().some(function(x){return x.namespace===a})});
g.Ro.prototype.Fg=g.YG(40,function(){return!1});
g.uS.prototype.YL=g.YG(38,function(a,x){this.app.vJ().YL(a,x)});
g.Hi.prototype.YL=g.YG(37,function(a,x){this.Tt.YL(a,x)});
g.v2.prototype.YL=g.YG(36,function(a,x){a=[a,x];g.nC(this,g.l0(this.provider),"cfi",a)});
g.Zc.prototype.YL=g.YG(35,function(a,x){this.qoe&&this.qoe.YL(a,x)});
g.tu.prototype.YL=g.YG(34,function(a,x){this.r0.YL(a,x)});
g.Ro.prototype.YL=g.YG(33,function(){});
g.uS.prototype.G$=g.YG(32,function(a,x,y){this.app.vJ().G$(a,x,y)});
g.Hi.prototype.G$=g.YG(31,function(a,x,y){this.Tt.G$(a,x,y)});
g.v2.prototype.G$=g.YG(30,function(a,x,y){if(this.N1!==a||this.Fn!==x)x=x==="rawcc"?"":x,y=[a,x,this.N1,y],g.Es(this.provider.S.aj())&&!this.iY&&y.push("sms.0"),g.nC(this,g.l0(this.provider),"cfs",y),this.N1=a,this.Fn=x,this.iY=!0});
g.Zc.prototype.G$=g.YG(29,function(a,x,y){this.qoe&&this.qoe.G$(a,x,y)});
g.tu.prototype.G$=g.YG(28,function(a,x,y){this.r0.G$(a,x,y)});
g.Ro.prototype.G$=g.YG(27,function(){});
g.fC.prototype.fE=g.YG(12,function(){return this.aY});
g.KF.prototype.fE=g.YG(11,function(){return this.vJ().f5()});
g.uS.prototype.f5=g.YG(10,function(){return this.app.fE()});
g.Hi.prototype.f5=g.YG(9,function(){return this.Tt.f5()});
g.tu.prototype.f5=g.YG(8,function(){var a;return((a=this.loader)==null?void 0:a.fE())||null});
g.Ro.prototype.f5=g.YG(7,function(){return null});
g.tE.prototype.Es=g.YG(1,function(a){return(a=this.d$(a))?a.T:0});
g.PL.prototype.Es=g.YG(0,function(){return 0});
var T1J=/#(.)(.)(.)/,PHn=/^#(?:[0-9a-f]{3}){1,2}$/i,hmp={aa:"Afar",ab:"Abkhazian",ace:"Acehnese",ach:"Acoli",ada:"Adangme",ady:"Adyghe",ae:"Avestan",aeb:"Tunisian Arabic",af:"Afrikaans",afh:"Afrihili",agq:"Aghem",ain:"Ainu",ak:"Akan",akk:"Akkadian",akz:"Alabama",ale:"Aleut",aln:"Gheg Albanian",alt:"Southern Altai",am:"Amharic",an:"Aragonese",ang:"Old English",anp:"Angika",ar:"Arabic",ar_001:"Arabic (world)",arc:"Aramaic",arn:"Mapuche",aro:"Araona",arp:"Arapaho",arq:"Algerian Arabic",ars:"Najdi Arabic",
arw:"Arawak",ary:"Moroccan Arabic",arz:"Egyptian Arabic",as:"Assamese",asa:"Asu",ase:"American Sign Language",ast:"Asturian",av:"Avaric",avk:"Kotava",awa:"Awadhi",ay:"Aymara",az:"Azerbaijani",az_Cyrl:"Azerbaijani (Cyrillic)",az_Latn:"Azerbaijani (Latin)",ba:"Bashkir",bal:"Baluchi",ban:"Balinese",bar:"Bavarian",bas:"Basaa",bax:"Bamun",bbc:"Batak Toba",bbj:"Ghomala",be:"Belarusian",bej:"Beja",bem:"Bemba",bew:"Betawi",bez:"Bena",bfd:"Bafut",bfq:"Badaga",bg:"Bulgarian",bgc:"Haryanvi",bgn:"Western Balochi",
bho:"Bhojpuri",bi:"Bislama",bik:"Bikol",bin:"Bini",bjn:"Banjar",bkm:"Kom",bla:"Siksik\u00e1",blo:"Anii",bm:"Bambara",bn:"Bangla",bo:"Tibetan",bpy:"Bishnupriya",bqi:"Bakhtiari",br:"Breton",bra:"Braj",brh:"Brahui",brx:"Bodo",bs:"Bosnian",bs_Cyrl:"Bosnian (Cyrillic)",bs_Latn:"Bosnian (Latin)",bss:"Akoose",bua:"Buriat",bug:"Buginese",bum:"Bulu",byn:"Blin",byv:"Medumba",ca:"Catalan",cad:"Caddo",car:"Carib",cay:"Cayuga",cch:"Atsam",ccp:"Chakma",ce:"Chechen",ceb:"Cebuano",cgg:"Chiga",ch:"Chamorro",chb:"Chibcha",
chg:"Chagatai",chk:"Chuukese",chm:"Mari",chn:"Chinook Jargon",cho:"Choctaw",chp:"Chipewyan",chr:"Cherokee",chy:"Cheyenne",ckb:"Central Kurdish",co:"Corsican",cop:"Coptic",cps:"Capiznon",cr:"Cree",crh:"Crimean Tatar",cs:"Czech",csb:"Kashubian",csw:"Swampy Cree",cu:"Church Slavic",cv:"Chuvash",cy:"Welsh",da:"Danish",dak:"Dakota",dar:"Dargwa",dav:"Taita",de:"German",de_AT:"German (Austria)",de_CH:"German (Switzerland)",del:"Delaware",den:"Slave",dgr:"Dogrib",din:"Dinka",dje:"Zarma",doi:"Dogri",dsb:"Lower Sorbian",
dua:"Duala",dum:"Middle Dutch",dv:"Divehi",dyo:"Jola-Fonyi",dyu:"Dyula",dz:"Dzongkha",dzg:"Dazaga",ebu:"Embu",ee:"Ewe",efi:"Efik",egy:"Ancient Egyptian",eka:"Ekajuk",el:"Greek",elx:"Elamite",en:"English",en_AU:"English (Australia)",en_CA:"English (Canada)",en_GB:"English (United Kingdom)",en_US:"English (United States)",enm:"Middle English",eo:"Esperanto",es:"Spanish",es_419:"Spanish (Latin America)",es_ES:"Spanish (Spain)",es_MX:"Spanish (Mexico)",et:"Estonian",eu:"Basque",ewo:"Ewondo",fa:"Persian",
fa_AF:"Persian (Afghanistan)",fan:"Fang",fat:"Fanti",ff:"Fula",ff_Adlm:"Fula (Adlam)",ff_Latn:"Fula (Latin)",fi:"Finnish",fil:"Filipino",fj:"Fijian",fo:"Faroese",fon:"Fon",fr:"French",fr_CA:"French (Canada)",fr_CH:"French (Switzerland)",frm:"Middle French",fro:"Old French",frr:"Northern Frisian",frs:"Eastern Frisian",fur:"Friulian",fy:"Western Frisian",ga:"Irish",gaa:"Ga",gay:"Gayo",gba:"Gbaya",gd:"Scottish Gaelic",gez:"Geez",gil:"Gilbertese",gl:"Galician",gmh:"Middle High German",gn:"Guarani",goh:"Old High German",
gon:"Gondi",gor:"Gorontalo",got:"Gothic",grb:"Grebo",grc:"Ancient Greek",gsw:"Swiss German",gu:"Gujarati",guz:"Gusii",gv:"Manx",gwi:"Gwich\u02bcin",ha:"Hausa",hai:"Haida",haw:"Hawaiian",he:"Hebrew",hi:"Hindi",hi_Latn:"Hindi (Latin)",hil:"Hiligaynon",hit:"Hittite",hmn:"Hmong",ho:"Hiri Motu",hr:"Croatian",hsb:"Upper Sorbian",ht:"Haitian Creole",hu:"Hungarian",hup:"Hupa",hy:"Armenian",hz:"Herero",ia:"Interlingua",iba:"Iban",ibb:"Ibibio",id:"Indonesian",ie:"Interlingue",ig:"Igbo",ii:"Sichuan Yi",ik:"Inupiaq",
ilo:"Iloko","in":"Indonesian",inh:"Ingush",io:"Ido",is:"Icelandic",it:"Italian",iu:"Inuktitut",iw:"Hebrew",ja:"Japanese",jbo:"Lojban",jgo:"Ngomba",jmc:"Machame",jpr:"Judeo-Persian",jrb:"Judeo-Arabic",jv:"Javanese",ka:"Georgian",kaa:"Kara-Kalpak",kab:"Kabyle",kac:"Kachin",kaj:"Jju",kam:"Kamba",kaw:"Kawi",kbd:"Kabardian",kbl:"Kanembu",kcg:"Tyap",kde:"Makonde",kea:"Kabuverdianu",kfo:"Koro",kg:"Kongo",kgp:"Kaingang",kha:"Khasi",kho:"Khotanese",khq:"Koyra Chiini",ki:"Kikuyu",kj:"Kuanyama",kk:"Kazakh",
kk_Cyrl:"Kazakh (Cyrillic)",kkj:"Kako",kl:"Kalaallisut",kln:"Kalenjin",km:"Khmer",kmb:"Kimbundu",kn:"Kannada",ko:"Korean",kok:"Konkani",kok_Deva:"Konkani (Devanagari)",kok_Latn:"Konkani (Latin)",kos:"Kosraean",kpe:"Kpelle",kr:"Kanuri",krc:"Karachay-Balkar",krl:"Karelian",kru:"Kurukh",ks:"Kashmiri",ks_Arab:"Kashmiri (Arabic)",ks_Deva:"Kashmiri (Devanagari)",ksb:"Shambala",ksf:"Bafia",ksh:"Colognian",ku:"Kurdish",kum:"Kumyk",kut:"Kutenai",kv:"Komi",kw:"Cornish",kxv:"Kuvi",kxv_Deva:"Kuvi (Devanagari)",
kxv_Latn:"Kuvi (Latin)",kxv_Orya:"Kuvi (Odia)",kxv_Telu:"Kuvi (Telugu)",ky:"Kyrgyz",la:"Latin",lad:"Ladino",lag:"Langi",lah:"Western Panjabi",lam:"Lamba",lb:"Luxembourgish",lez:"Lezghian",lg:"Ganda",li:"Limburgish",lij:"Ligurian",lkt:"Lakota",lmo:"Lombard",ln:"Lingala",lo:"Lao",lol:"Mongo",loz:"Lozi",lrc:"Northern Luri",lt:"Lithuanian",lu:"Luba-Katanga",lua:"Luba-Lulua",lui:"Luiseno",lun:"Lunda",luo:"Luo",lus:"Mizo",luy:"Luyia",lv:"Latvian",mad:"Madurese",maf:"Mafa",mag:"Magahi",mai:"Maithili",mak:"Makasar",
man:"Mandingo",mas:"Masai",mde:"Maba",mdf:"Moksha",mdr:"Mandar",men:"Mende",mer:"Meru",mfe:"Morisyen",mg:"Malagasy",mga:"Middle Irish",mgh:"Makhuwa-Meetto",mgo:"Meta\u02bc",mh:"Marshallese",mi:"M\u0101ori",mic:"Mi'kmaw",min:"Minangkabau",mk:"Macedonian",ml:"Malayalam",mn:"Mongolian",mnc:"Manchu",mni:"Manipuri",mni_Beng:"Manipuri (Bangla)",mo:"Romanian",moh:"Mohawk",mos:"Mossi",mr:"Marathi",ms:"Malay",mt:"Maltese",mua:"Mundang",mul:"Multiple languages",mus:"Muscogee",mwl:"Mirandese",mwr:"Marwari",
my:"Burmese",mye:"Myene",myv:"Erzya",mzn:"Mazanderani",na:"Nauru",nap:"Neapolitan",naq:"Nama",nb:"Norwegian Bokm\u00e5l",nd:"North Ndebele",nds:"Low German",nds_NL:"Low German (Netherlands)",ne:"Nepali","new":"Newari",ng:"Ndonga",nia:"Nias",niu:"Niuean",nl:"Dutch",nl_BE:"Dutch (Belgium)",nmg:"Kwasio",nn:"Norwegian Nynorsk",nnh:"Ngiemboon",no:"Norwegian",nog:"Nogai",non:"Old Norse",nqo:"N\u2019Ko",nr:"South Ndebele",nso:"Northern Sotho",nus:"Nuer",nv:"Navajo",nwc:"Classical Newari",ny:"Nyanja",nym:"Nyamwezi",
nyn:"Nyankole",nyo:"Nyoro",nzi:"Nzima",oc:"Occitan",oj:"Ojibwa",om:"Oromo",or:"Odia",os:"Ossetic",osa:"Osage",ota:"Ottoman Turkish",pa:"Punjabi",pa_Arab:"Punjabi (Arabic)",pa_Guru:"Punjabi (Gurmukhi)",pag:"Pangasinan",pal:"Pahlavi",pam:"Pampanga",pap:"Papiamento",pau:"Palauan",pcm:"Nigerian Pidgin",peo:"Old Persian",phn:"Phoenician",pi:"Pali",pl:"Polish",pon:"Pohnpeian",prg:"Prussian",pro:"Old Proven\u00e7al",ps:"Pashto",pt:"Portuguese",pt_BR:"Portuguese (Brazil)",pt_PT:"Portuguese (Portugal)",qu:"Quechua",
raj:"Rajasthani",rap:"Rapanui",rar:"Rarotongan",rm:"Romansh",rn:"Rundi",ro:"Romanian",ro_MD:"Romanian (Moldova)",rof:"Rombo",rom:"Romany",ru:"Russian",rup:"Aromanian",rw:"Kinyarwanda",rwk:"Rwa",sa:"Sanskrit",sad:"Sandawe",sah:"Yakut",sam:"Samaritan Aramaic",saq:"Samburu",sas:"Sasak",sat:"Santali",sat_Olck:"Santali (Ol Chiki)",sba:"Ngambay",sbp:"Sangu",sc:"Sardinian",scn:"Sicilian",sco:"Scots",sd:"Sindhi",sd_Arab:"Sindhi (Arabic)",sd_Deva:"Sindhi (Devanagari)",se:"Northern Sami",see:"Seneca",seh:"Sena",
sel:"Selkup",ses:"Koyraboro Senni",sg:"Sango",sga:"Old Irish",sh:"Serbo-Croatian",shi:"Tachelhit",shi_Latn:"Tachelhit (Latin)",shi_Tfng:"Tachelhit (Tifinagh)",shn:"Shan",shu:"Chadian Arabic",si:"Sinhala",sid:"Sidamo",sk:"Slovak",sl:"Slovenian",sm:"Samoan",sma:"Southern Sami",smj:"Lule Sami",smn:"Inari Sami",sms:"Skolt Sami",sn:"Shona",snk:"Soninke",so:"Somali",sog:"Sogdien",sq:"Albanian",sr:"Serbian",sr_Cyrl:"Serbian (Cyrillic)",sr_Latn:"Serbian (Latin)",srn:"Sranan Tongo",srr:"Serer",ss:"Swati",
ssy:"Saho",st:"Southern Sotho",su:"Sundanese",su_Latn:"Sundanese (Latin)",suk:"Sukuma",sus:"Susu",sux:"Sumerian",sv:"Swedish",sw:"Swahili",sw_CD:"Swahili (Congo - Kinshasa)",swb:"Comorian",syc:"Classical Syriac",syr:"Syriac",szl:"Silesian",ta:"Tamil",te:"Telugu",tem:"Timne",teo:"Teso",ter:"Tereno",tet:"Tetum",tg:"Tajik",th:"Thai",ti:"Tigrinya",tig:"Tigre",tiv:"Tiv",tk:"Turkmen",tkl:"Tokelau",tl:"Tagalog",tlh:"Klingon",tli:"Tlingit",tmh:"Tamashek",tn:"Tswana",to:"Tongan",tog:"Nyasa Tonga",tok:"Toki Pona",
tpi:"Tok Pisin",tr:"Turkish",trv:"Taroko",ts:"Tsonga",tsi:"Tsimshian",tt:"Tatar",tum:"Tumbuka",tvl:"Tuvalu",tw:"Twi",twq:"Tasawaq",ty:"Tahitian",tyv:"Tuvinian",tzm:"Central Atlas Tamazight",udm:"Udmurt",ug:"Uyghur",uga:"Ugaritic",uk:"Ukrainian",umb:"Umbundu",ur:"Urdu",uz:"Uzbek",uz_Arab:"Uzbek (Arabic)",uz_Cyrl:"Uzbek (Cyrillic)",uz_Latn:"Uzbek (Latin)",vai:"Vai",vai_Latn:"Vai (Latin)",vai_Vaii:"Vai (Vai)",ve:"Venda",vec:"Venetian",vi:"Vietnamese",vmw:"Makhuwa",vo:"Volap\u00fck",vot:"Votic",vun:"Vunjo",
wa:"Walloon",wae:"Walser",wal:"Wolaytta",war:"Waray",was:"Washo",wo:"Wolof",xal:"Kalmyk",xh:"Xhosa",xnr:"Kangri",xog:"Soga",yao:"Yao",yap:"Yapese",yav:"Yangben",ybb:"Yemba",yi:"Yiddish",yo:"Yoruba",yrl:"Nheengatu",yue:"Cantonese",yue_Hans:"Cantonese (Simplified)",yue_Hant:"Cantonese (Traditional)",za:"Zhuang",zap:"Zapotec",zbl:"Blissymbols",zen:"Zenaga",zgh:"Standard Moroccan Tamazight",zh:"Chinese",zh_Hans:"Chinese (Simplified)",zh_Hant:"Chinese (Traditional)",zh_TW:"Chinese (Taiwan)",zu:"Zulu",
zun:"Zuni",zxx:"No linguistic content",zza:"Zaza"};g.d(mkh,g.Cf);mkh.prototype.DF=function(a){var x=this.R7.vN();if(x&&x.Qn()){x=x.Qn().textTracks;x=g.W(x);for(var y=x.next();!y.done;y=x.next())y=y.value,y.kind==="subtitles"&&!this.B.has(y.language)&&y.language&&(g.wE(this.T,new g.qc({languageCode:y.language,languageName:y.language,kind:y.kind,id:y.id,displayName:y.label,vss_id:"."+y.language})),this.B.add(y.language))}g.bn(this.T).length>0&&a.mu()};
Jp.prototype.contains=function(a){a=g.SS(this.segments,a);return a>=0||a<0&&(-a-1)%2===1};
Jp.prototype.length=function(){return this.segments.length/2};
g.d(EMh,g.A);g.C=EMh.prototype;g.C.m6=function(){g.A.prototype.m6.call(this);this.B&&this.B.cancel()};
g.C.aP=function(){this.seekTo(this.player.getCurrentTime())};
g.C.seekTo=function(a){a-=this.player.GY();var x=this.T;this.T=g.Vn(this.JP.ol(a).gS);x!==this.T&&this.BJ&&this.BJ()};
g.C.reset=function(){this.U=new Jp;this.D=-1;this.B&&(this.B.cancel(),this.B=null)};
g.C.CP=function(){this.hP();var a;if(a=this.T!=null)a=this.T,a=a.JP.lJ(a);if(a&&!this.B&&!(this.T&&this.T.startTime-this.player.getCurrentTime()>30)){a=this.T;a=a.JP.hm(a);var x=a.gS[0],y;if((y=this.player.getVideoData())==null?0:y.enableServerStitchedDai)if(y=this.player.f5()){var D=x.JP.info.id,M=x.bY,N=a.gS[0].U;if(this.policy.e8){if(y=g.Qk7(y,N,M,D,3))a.U=y}else if(D=y.Nr(N,M,D,3))if(N=2,y.Tf.has(M)?N=0:g.DKq(y,M)&&(N=1),y=N,y===0)D&&(a.T=new g.d8(D));else if(y===2){this.Y.start();sZF(this)&&
this.seekTo(this.player.getCurrentTime());return}}x.JP.index.OP(x.bY)?(this.U.contains(a.gS[0].bY)||B1y(this,a),this.T=g.Vn(a.gS)):sZF(this)&&this.seekTo(this.player.getCurrentTime())}this.Y.start()};
g.d(GB,g.Cf);g.C=GB.prototype;g.C.pH=function(a,x,y){var D=this;this.g$();x=fzP(this,a.getId());x||(x=a.languageCode,x=this.B.isManifestless?gMF(this,x,"386"):gMF(this,x));if(x){var M=(x.index.Es(x.index.QM())-x.index.getStartTime(x.index.QM()))*1E3,N=new g.zBz(this.L.j());this.U=new EMh(N,this.L,x,function(F,c){y.eh(F,a,c,M)},this.Y||g.$f(x.info),function(){D.U&&D.U.reset();
D.D=!0})}};
g.C.Dh=function(){var a=this.D;this.D=!1;return a};
g.C.DF=function(a){var x=this.L.j().C("html5_fallback_if_rawcc_missing");var y=this.B.T.rawcc!=null;if(!this.Y||!y&&x)x=this.B.isManifestless?$kL(this,"386"):$kL(this);else{if(!y){g.Lc(this.logger,386248249,"rawcc used but unavailable");return}x=[new g.qc({id:"rawcc",languageCode:"rawcc",languageName:"CC1",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"}),new g.qc({id:"rawcc",languageCode:"rawcc",languageName:"CC3",is_servable:!0,is_default:!0,is_translateable:!1,vss_id:".en"})]}x=g.W(x);
for(y=x.next();!y.done;y=x.next())g.wE(this.T,y.value);a.mu()};
g.C.g$=function(){this.U&&(this.U.dispose(),this.U=null)};
g.C.Rl=function(){return""};
var WQ=/^#(?:[0-9a-f]{3}){1,2}$/i;var Ais=["left","right","center","justify"];g.d(Q7,g.O);g.C=Q7.prototype;g.C.qt=function(a,x){this.YG=a;this.EJ=x;var y=g.Le(this.element,this.element.parentElement);this.zt=a-y.x;this.iY=x-y.y};
g.C.VG=function(a,x){if(a!==this.YG||x!==this.EJ){g.FR(this.element,"ytp-dragging")||g.zt(this.element,"ytp-dragging");var y=g.Ce(this.element);a=a-this.zt-.02*this.AK;var D=x-this.iY-.02*this.Vn,M=(a+y.width/2)/this.maxWidth*3;M=Math.floor(g.Dz(M,0,2));var N=(D+y.height/2)/this.maxHeight*3;N=Math.floor(g.Dz(N,0,2));x=M+N*3;a=(a+M/2*y.width)/this.maxWidth;a=g.Dz(a,0,1)*100;y=(D+N/2*y.height)/this.maxHeight;y=g.Dz(y,0,1)*100;this.B.params.uM=x;this.B.params.VM=y;this.B.params.bb=a;this.B.params.isDefault=
!1;this.T.uM=x;this.T.VM=y;this.T.bb=a;this.T.isDefault=!1;this.dS.uM=x;this.dS.VM=y;this.dS.bb=a;this.dS.isDefault=!1;this.FZ()}};
g.C.EF=function(){g.o9(this.element,"ytp-dragging")};
g.C.FZ=function(){this.Ii(this.D)};
g.C.Ii=function(a){var x=this.S8?0:Math.min(this.lj(),this.maxWidth),y=this.YJ(),D=this.S8;if(D){var M=getComputedStyle(this.U.parentNode);M=S7(M.borderLeftWidth)+S7(M.borderRightWidth)+S7(M.paddingLeft)+S7(M.paddingRight)}else M=0;var N=M;M="";this.B.params.GM===3&&(M="rotate(180deg)");var F=D?"calc(96% - "+N+"px)":"96%";g.F7(this.element,{top:0,left:0,right:"",bottom:"",width:x?x+"px":"",height:y?y+"px":"","max-width":F,"max-height":F,margin:"",transform:""});this.d4(a);M={transform:M,top:"",left:"",
width:x?x+"px":"",height:y?y+"px":"","max-width":"","max-height":""};var c=this.T.bb*.96+2;F=this.T.uM;switch(F){case 0:case 3:case 6:(D=this.T.q0.fontSizeIncrement)&&D>0&&this.T.GM!==2&&this.T.GM!==3&&(c=Math.max(c/(1+D*2),2));M.left=c+"%";break;case 1:case 4:case 7:M.left=c+"%";c=this.U.offsetWidth;x||c?(x=x||c+1,M.width=x+"px",M["margin-left"]=D?x/-2-N/2+"px":x/-2+"px"):M.transform+=" translateX(-50%)";break;case 2:case 5:case 8:M.right=100-c+"%"}D=this.T.VM*.96+2;switch(F){case 0:case 1:case 2:M.top=
D+"%";break;case 3:case 4:case 5:M.top=D+"%";(y=y||this.element.clientHeight)?(M.height=y+"px",M["margin-top"]=y/-2+"px"):M.transform+=" translateY(-50%)";break;case 6:case 7:case 8:M.bottom=100-D+"%"}g.F7(this.element,M);if(this.N){y=this.U.offsetHeight;D=1;for(x=0;x<a.length;x++)M=a[x],typeof M.text==="string"&&(D+=M.text.split("\n").length-1,M.append||x===0||D++);y/=D;this.N.style.height=y+"px";this.N.style.width=y+"px";this.element.style.paddingLeft=y+5+"px";this.element.style.paddingRight=y+
5+"px";a=Number(this.element.style.marginLeft.replace("px",""))-y-5;y=Number(this.element.style.marginRight.replace("px",""))-y-5;this.element.style.marginLeft=a+"px";this.element.style.marginRight=y+"px"}};
g.C.d4=function(a){var x;for(x=0;x<a.length&&a[x]===this.D[x];x++);if(this.UJ||this.D.length>x)x=0,this.UJ=!1,this.D=[],this.Y=this.N1=this.yP=null,g.hi(this.U);for(;x<a.length;x++)Vqh(this,a[x])};
g.C.lj=function(){return 0};
g.C.YJ=function(){return 0};
g.C.toString=function(){return g.O.prototype.toString.call(this)};tq7.prototype.clear=function(){this.J=this.time=this.mode=0;this.T=[];this.reset()};
tq7.prototype.reset=function(){this.mode=0;this.U.reset(0);this.N.reset(1)};
var XKy=[128,1,2,131,4,133,134,7,8,137,138,11,140,13,14,143,16,145,146,19,148,21,22,151,152,25,26,155,28,157,158,31,32,161,162,35,164,37,38,167,168,41,42,171,44,173,174,47,176,49,50,179,52,181,182,55,56,185,186,59,188,61,62,191,64,193,194,67,196,69,70,199,200,73,74,203,76,205,206,79,208,81,82,211,84,213,214,87,88,217,218,91,220,93,94,223,224,97,98,227,100,229,230,103,104,233,234,107,236,109,110,239,112,241,242,115,244,117,118,247,248,121,122,251,124,253,254,127,0,129,130,3,132,5,6,135,136,9,10,139,
12,141,142,15,144,17,18,147,20,149,150,23,24,153,154,27,156,29,30,159,160,33,34,163,36,165,166,39,40,169,170,43,172,45,46,175,48,177,178,51,180,53,54,183,184,57,58,187,60,189,190,63,192,65,66,195,68,197,198,71,72,201,202,75,204,77,78,207,80,209,210,83,212,85,86,215,216,89,90,219,92,221,222,95,96,225,226,99,228,101,102,231,232,105,106,235,108,237,238,111,240,113,114,243,116,245,246,119,120,249,250,123,252,125,126,255];K5.prototype.set=function(a){this.type=a};
K5.prototype.get=function(){return this.type};
L5.prototype.clear=function(){this.state=0};
L5.prototype.update=function(){this.state=this.state===2?1:0};
L5.prototype.hC=function(){return this.state!==0};
L5.prototype.matches=function(a,x){return this.hC()&&a===this.vL&&x===this.K4};
adD.prototype.reset=function(){this.timestamp=this.T=0};
wS.prototype.updateTime=function(a){for(var x=1;x<=15;++x)for(var y=1;y<=32;++y)this.J[x][y].timestamp=a};
wS.prototype.debugString=function(){for(var a="\n",x=1;x<=15;++x){for(var y=1;y<=32;++y){var D=this.J[x][y];a=D.T===0?a+"_":a+String.fromCharCode(D.T)}a+="\n"}return a};
wS.prototype.reset=function(a){for(var x=0;x<=15;x++)for(var y=0;y<=32;y++)this.J[x][y].reset();this.U=a;this.T=0;this.B=this.row=1};
var xFF=[32,33,34,35,36,37,38,39,40,41,225,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,233,93,237,243,250,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,231,247,209,241,9632],y3s=[174,176,189,191,8482,162,163,9834,224,32,232,226,234,238,244,251],j_V=[193,201,211,218,220,252,8216,161,42,39,9473,169,8480,183,8220,8221,192,194,199,200,202,203,235,
206,207,239,212,217,249,219,171,187],DFF=[195,227,205,204,236,210,242,213,245,123,125,92,94,95,124,126,196,228,214,246,223,165,164,9475,197,229,216,248,9487,9491,9495,9499];zIY.prototype.reset=function(a,x){this.N=x;this.style.set(2);this.B=this.D;this.U=this.Y;this.T=this.B;var y=(a<<2)+(x<<1);this.D.reset(y);this.Y.reset(y);this.text.reset((a<<2)+(x<<1)+1)};
riL.prototype.reset=function(a){this.N=a;this.B.clear();this.U=this.J;this.J.reset(a,0);this.D.reset(a,1)};GXV.prototype.U=function(){};g.d(n5,g.gr);n5.prototype.toString=function(){return g.gr.prototype.toString.call(this)};g.d(vQ,g.A);vQ.prototype.reset=function(){};g.d(PQ,g.gr);PQ.prototype.toString=function(){return g.gr.prototype.toString.call(this)};
var TB=0;g.d(lZ,vQ);lZ.prototype.reset=function(){this.Y={};this.B=this.T=null;this.D=!0};
lZ.prototype.J=function(a,x){a=a.firstChild;a.getAttribute("format");x=x||0;Number.isFinite(x);a=Array.from(a.childNodes);a=g.W(a);for(var y=a.next();!y.done;y=a.next())if(y=y.value,y.nodeType===1)switch(y.tagName){case "head":var D=y;break;case "body":var M=y}if(D)for(D=Array.from(D.childNodes),D=g.W(D),a=D.next();!a.done;a=D.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "pen":y=a.getAttribute("id");var N=this.pens,F={},c=a.getAttribute("p");c&&Object.assign(F,this.pens[c]);c=uZ(a,"b");
c!=null&&(F.bold=c);c=uZ(a,"i");c!=null&&(F.italic=c);c=uZ(a,"u");c!=null&&(F.underline=c);c=m1(a,"et");c!=null&&(F.charEdgeStyle=c);c=m1(a,"of");c!=null&&(F.offset=c);c=EZ(a,"bc");c!=null&&(F.background=c);c=EZ(a,"ec");c!=null&&(F.Rm=c);c=EZ(a,"fc");c!=null&&(F.color=c);c=m1(a,"fs");c!=null&&c!==0&&(F.fontFamily=c);c=kP(a,"sz");c!==void 0&&(F.fontSizeIncrement=c/100-1);c=kP(a,"bo");c!==void 0&&(F.backgroundOpacity=c/255);c=kP(a,"fo");c!==void 0&&(F.textOpacity=c/255);c=m1(a,"rb");c!=null&&c!==10&&
c!==0&&(F.P3=c>10?c-1:c);a=m1(a,"hg");a!=null&&(F.Dp=a);N[y]=F;break;case "ws":y=a.getAttribute("id");this.BJ[y]=LGD(this,a);break;case "wp":y=a.getAttribute("id"),this.V[y]=wcP(this,a)}if(M){D=[];M=Array.from(M.childNodes);M=g.W(M);for(a=M.next();!a.done;a=M.next())if(a=a.value,a.nodeType===1)switch(a.tagName){case "w":this.T=C2D(this,a,x,!1);(a=this.Y[this.T.id])&&a.end>this.T.start&&(a.end=this.T.start);this.Y[this.T.id]=this.T;D.push(this.T);break;case "p":var J=a;c=x;y=[];N=J.getAttribute("w")||
this.N;F=!!uZ(J,"a");c=(kP(J,"t")||0)+c;var G=kP(J,"d")||5E3;F||(!this.D&&this.B&&this.B.windowId===N&&this.B.end>c&&(this.B.end=c),this.B&&this.B.text==="\n"&&(this.B.text=""));var Q=F?6:5,S=J.getAttribute("p");S=S?this.pens[S]:null;var K=Array.from(J.childNodes);K.length&&(this.D=J.getAttribute("d")!=null);for(J=0;J<K.length;J++){var L=K[J],w=void 0;J>0&&(F=!0);var Z=void 0;L.nodeType===1&&(Z=L);if(Z&&Z.tagName==="s"){if((L=(L=Z.getAttribute("p"))?this.pens[L]:null)&&L.P3&&(L.P3===1?(L=K.slice(J,
J+4),L.length===4&&(w=Sk7(c,G,N,F,Q,L,this.pens),J+=3)):w=Sk7(c,G,N,F,Q,[Z],this.pens)),!w){var v=Z;w=c;Z=G;L=N;var m=F,u=Q,E=v.textContent?v.textContent:"",h=v.getAttribute("p");h=h?this.pens[h]:null;v=kP(v,"t")||0;w=new n5(w+v,Z-v,u,L,E,m,h)}}else w=new n5(c,G,Q,N,L.textContent||"",F,S);y.push(w);this.B=w}if(y.length>0)for(y[0].windowId===this.N&&(this.T=C2D(this,a,x,!0),D.push(this.T)),a=g.W(y),y=a.next();!y.done;y=a.next())y=y.value,y.windowId=this.T.id,this.T.T.push(y),D.push(y)}x=D}else x=[];
return x};var jGJ=new Map([[9,1],[10,1],[11,2],[12,3],[13,4],[14,5]]);g.d(sZ,vQ);sZ.prototype.reset=function(){this.B.clear()};
sZ.prototype.J=function(a,x){var y=JSON.parse(a);if(!y)return[];if(y.pens){a=0;for(var D=g.W(y.pens),M=D.next();!M.done;M=D.next()){M=M.value;var N={},F=M.pParentId;F&&Object.assign(N,this.T.get(F));M.bAttr&&(N.bold=!0);M.iAttr&&(N.italic=!0);M.uAttr&&(N.underline=!0);F=M.ofOffset;F!=null&&(N.offset=F);M.szPenSize!==void 0&&(N.fontSizeIncrement=M.szPenSize/100-1);F=M.etEdgeType;F!=null&&(N.charEdgeStyle=F);M.ecEdgeColor!==void 0&&(N.Rm=BQ(M.ecEdgeColor));F=M.fsFontStyle;F!=null&&F!==0&&(N.fontFamily=
F);M.fcForeColor!==void 0&&(N.color=BQ(M.fcForeColor));M.foForeAlpha!==void 0&&(N.textOpacity=M.foForeAlpha/255);M.bcBackColor!==void 0&&(N.background=BQ(M.bcBackColor));M.boBackAlpha!==void 0&&(N.backgroundOpacity=M.boBackAlpha/255);(F=M.rbRuby)&&F!==10&&(N.P3=F>10?F-1:F,N.textEmphasis=jGJ.get(N.P3));M.hgHorizGroup&&(N.Dp=M.hgHorizGroup);this.T.set(a++,N)}}if(y.wsWinStyles)for(a=0,D=g.W(y.wsWinStyles),M=D.next();!M.done;M=D.next())M=M.value,N={},(F=M.wsParentId)?Object.assign(N,this.N.get(F)):Object.assign(N,
this.D),M.mhModeHint!==void 0&&(N.a6=M.mhModeHint),M.juJustifCode!==void 0&&(N.textAlign=M.juJustifCode),M.pdPrintDir!==void 0&&(N.GM=M.pdPrintDir),M.sdScrollDir!==void 0&&(N.Ql=M.sdScrollDir),M.wfcWinFillColor!==void 0&&(N.windowColor=BQ(M.wfcWinFillColor)),M.wfoWinFillAlpha!==void 0&&(N.windowOpacity=M.wfoWinFillAlpha/255),this.N.set(a++,N);if(y.wpWinPositions)for(a=0,D=g.W(y.wpWinPositions),M=D.next();!M.done;M=D.next())M=M.value,N={},(F=M.wpParentId)&&Object.assign(N,this.U.get(F)),M.ahHorPos!==
void 0&&(N.bb=M.ahHorPos),M.apPoint!==void 0&&(N.uM=M.apPoint),M.avVerPos!==void 0&&(N.VM=M.avVerPos),M.ccCols!==void 0&&(N.AS=M.ccCols),M.rcRows!==void 0&&(N.n4=M.rcRows),this.U.set(a++,N);if(y.events){a=[];y=g.W(y.events);for(D=y.next();!D.done;D=y.next()){var c=D.value;M=(c.tStartMs||0)+x;N=c.dDurationMs||0;if(c.id)F=String(c.id),D=qks(this,c,M,N,F),a.push(D),this.B.set(F,D);else{c.wWinId?F=c.wWinId.toString():(F="_"+TB++,D=qks(this,c,M,N,F),a.push(D),this.B.set(F,D));D=a;var J=c;N===0&&(N=5E3);
c=this.B.get(F);var G=!!J.aAppend,Q=G?6:5,S=J.segs,K=null;J.pPenId&&(K=this.T.get(J.pPenId));for(J=0;J<S.length;J++){var L=S[J],w=L.utf8;if(w){var Z=L.tOffsetMs||0,v=null;L.pPenId&&(v=this.T.get(L.pPenId));if((c.params.a6!=null?c.params.a6:c.T.length>1?1:0)===2&&G&&w==="\n")continue;L=null;var m=[],u;if(u=v&&v.P3===1){u=S;var E=J;if(E+3>=u.length||!u[E+1].pPenId||!u[E+2].pPenId||!u[E+3].pPenId)u=!1;else{var h=u[E+1].pPenId;(h=this.T.get(h))&&h.P3&&h.P3===2?(h=u[E+2].pPenId,h=this.T.get(h),!h||!h.P3||
h.P3<3?u=!1:(h=u[E+3].pPenId,u=(h=this.T.get(h))&&h.P3&&h.P3===2?!0:!1)):u=!1}}if(u)Z=S[J+1].utf8,L=S[J+3].utf8,u=S[J+2].utf8,E=this.T.get(S[J+2].pPenId),w=Q_D(w,Z,u,L,E),L=new n5(M,N,Q,F,w,G,v),J+=3;else{if(w.indexOf("<")>-1){var V=void 0;m=v;u=K;E=M;h=N;var H=Z,j6=Q,e=G,as=[],z7=g.rp("<html>"+w+"</html>");if(!z7.getElementsByTagName("parsererror").length&&((V=z7.firstChild)==null?0:V.childNodes.length))for(V=g.W(z7.firstChild.childNodes),z7=V.next();!z7.done;z7=V.next()){z7=z7.value;var Qq=void 0,
DJ=void 0,nz=(DJ=(Qq=z7.textContent)==null?void 0:Qq.replace(/\n/g,""))!=null?DJ:"";if(z7.nodeType!==3||nz&&nz.match(/^ *$/)==null){Qq={};Object.assign(Qq,m||u);DJ=void 0;switch((DJ=z7)==null?void 0:DJ.tagName){case "b":Qq.bold=!0;break;case "i":Qq.italic=!0;break;case "u":Qq.underline=!0}as.push(new n5(E+H,h-H,j6,c.id,nz,e,Qq))}}m=as}m.length||(m=[new n5(M+Z,N-Z,Q,c.id,w,G,v||K)])}if(m.length)for(G=g.W(m),v=G.next();!v.done;v=G.next())v=v.value,D.push(v),c.T.push(v);else L&&(D.push(L),c.T.push(L))}G=
!0}}}x=a}else x=[];return x};g.d(hp,g.Cf);hp.prototype.pH=function(a,x,y){vMp(this.videoData.videoId,a.vssId,y.eh)};
hp.prototype.DF=function(a){if(this.audioTrack)for(var x=g.W(this.audioTrack.captionTracks),y=x.next();!y.done;y=x.next())g.wE(this.T,y.value);a.mu()};g.d($P,Q7);$P.prototype.d4=function(a){var x=this.B.T;Q7.prototype.d4.call(this,a);for(a=a.length;a<x.length;a++){var y=x[a];if(N&&y.T===M)var D=N;else{D={};Object.assign(D,y.T);Object.assign(D,DZP);var M=y.T;var N=D}Vqh(this,y,D)}};
var DZP={rPR:!0};g.d(f5,GXV);f5.prototype.U=function(a,x,y,D,M){if(y<D){var N="_"+TB++;y=y/1E3-this.D;D=D/1E3-this.D;a=new PQ(y,D-y,5,N,{textAlign:0,uM:0,bb:x*2.5,VM:a*5.33});M=new n5(y,D-y,5,N,M);this.B.push(a);this.B.push(M)}};
g.d(YP,vQ);YP.prototype.J=function(a){a=new f5(a,a.byteLength,this.B);if(dFn(a)){for(;a.byteOffset<a.T.byteLength;)for(a.version===0?a.J=RT(a)*(1E3/45):a.version===1&&(a.J=RT(a)*4294967296+RT(a)),a.N=gS(a);a.N>0;a.N--){var x=gS(a),y=gS(a),D=gS(a);x&4&&(x&3)===this.track&&(this.track===0||this.track===1)&&(x=this.T,x.T.push({time:a.J,type:this.track,Op:y,x3:D,order:x.T.length}))}emp(this.T,a);return a.B}return[]};
YP.prototype.reset=function(){this.T.clear()};g.d(Ap,Q7);g.C=Ap.prototype;g.C.FZ=function(){g.a9(this.tf)};
g.C.Hg=function(){this.element.removeEventListener("transitionend",this.Hg,!1);g.o9(this.element,"ytp-rollup-mode");this.Ii(this.bO,!0)};
g.C.YJ=function(){return this.J?this.cJ:this.V};
g.C.lj=function(){return this.J?this.V:this.cJ};
g.C.Ii=function(a,x){this.bO=a;if(this.B.params.n4){for(var y=0,D=0;D<this.D.length&&y<a.length;D++)this.D[D]===a[y]&&y++;y>0&&y<a.length&&(a=this.D.concat(a.slice(y)));this.Af=this.cJ;this.V=this.cJ=0;Q7.prototype.Ii.call(this,a);P27(this,x)}Q7.prototype.Ii.call(this,a)};TUV.prototype.unload=function(){this.T!=null&&(this.L.removeEventListener("sabrCaptionsDataLoaded",this.T),this.T=null);this.dF=[];this.L.publish("sabrCaptionsBufferedRangesUpdated",this.dF)};
TUV.prototype.cB=function(a){return{formatId:g.g_(a.info.JP.info,this.w0),bY:a.info.bY+(this.w0?0:1),startTimeMs:a.info.U*1E3,durationMs:a.info.Y*1E3}};g.d(UZ,g.Cf);UZ.prototype.pH=function(a,x,y){this.g$();x=a.getId();x=x!=null&&x in this.B.T?this.B.T[x]:null;x||(x=a.languageCode,x=this.B.isManifestless?mFs(this,x,"386"):mFs(this,x));x&&(this.U=a,this.D=x,kXJ(this.Y,y),this.L.publish("sabrCaptionsTrackChanged",g.g_(x.info,this.B.w0)))};
UZ.prototype.DF=function(a){var x=this.B.isManifestless?u77(this,"386"):u77(this);x=g.W(x);for(var y=x.next();!y.done;y=x.next())g.wE(this.T,y.value);a.mu()};
UZ.prototype.g$=function(){this.U&&(this.U=this.D=null,this.Y.unload(),this.L.publish("sabrCaptionsTrackChanged",null))};
UZ.prototype.Rl=function(){return""};var s_y="WEBVTT".split("").map(function(a){return a.charCodeAt(0)});
g.d(E8L,vQ);
E8L.prototype.J=function(a,x){a instanceof ArrayBuffer&&(a=g.Cm(new Uint8Array(a)));var y=[];a=a.split(M2p);for(var D=1;D<a.length;D++){var M=a[D],N=x;if(M!==""&&!NPy.test(M)){var F=FeF.exec(M);if(F&&F.length>=4){var c=$Fy(F[1]),J=$Fy(F[2])-c;c+=N;var G=(F=F[3])?F.split(" "):[];F={};var Q=null;var S="";var K=null,L="";G=g.W(G);for(var w=G.next();!w.done;w=G.next())if(w=w.value.split(":"),w.length===2){var Z=w[1];switch(w[0]){case "line":w=Z.split(",");w[0].endsWith("%")&&(Q=w[0],F.VM=Number.parseInt(Q,
10),w.length===2&&(S=w[1].trim()));break;case "position":w=Z.split(",");K=w[0];F.bb=Number.parseInt(K,10);w.length===2&&(L=w[1].trim());break;case "align":switch(Z){case "start":F.textAlign=0;break;case "middle":F.textAlign=2;break;case "end":F.textAlign=1}}}Q||S||(S="end");if(!K)switch(F.textAlign){case 0:F.bb=0;break;case 1:F.bb=100;break;case 2:F.bb=50}if(F.textAlign!=null){Q=0;switch(S){case "center":Q+=3;break;case "end":Q+=6;break;default:Q+=0}switch(L){case "line-left":Q+=0;break;case "center":Q+=
1;break;case "line-right":Q+=2;break;default:switch(F.textAlign){case 0:Q+=0;break;case 2:Q+=1;break;case 1:Q+=2}}S=Q<0||Q>8?7:Q;F.uM=S}M=M.substring(FeF.lastIndex).replace(/[\x01-\x09\x0b-\x1f]/g,"");L=F;F=M;M={};if(F.indexOf("<")<0&&F.indexOf("&")<0)N=fdL(c,J,5,L),J=new n5(c,J,5,N.id,F,!1,g.sJ(M)?void 0:M),y.push(N),y.push(J),N.T.push(J);else for(S=F.split(z9h),S.length===1?(F=5,L=fdL(c,J,F,L)):(Q=F=6,L=Object.assign({AS:32},L),L=new PQ(c,J,Q,"_"+TB++,L)),y.push(L),Q=c,K=0;K<S.length;K++)G=S[K],
K%2===0?(w=g.rp("<html>"+G+"</html>"),w.getElementsByTagName("parsererror").length?(Z=w.createElement("span"),Z.appendChild(w.createTextNode(G))):Z=w.firstChild,hIF(this,Q,J-(Q-c),F,L,K>0,Z,M,y)):Q=$Fy(G)+N}FeF.lastIndex=0}}return y};
var NPy=/^NOTE/,M2p=/(?:\r\n|\r|\n){2,}/,FeF=RegExp("^((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})[\\t ]+--\x3e[\\t ]+((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})(?:[\\t ]*)(.*)(?:\\r\\n|\\r|\\n)","gm"),z9h=RegExp("<((?:[\\d]{2}:)?[\\d]{2}:[\\d]{2}\\.[\\d]{3})>");g.d(HQ,g.A);HQ.prototype.clear=function(){this.T&&this.T.dispose();this.T=null};
HQ.prototype.reset=function(){this.T&&this.T.reset()};
HQ.prototype.m6=function(){g.A.prototype.m6.call(this);this.clear()};var p5={windowColor:"#080808",windowOpacity:0,textAlign:2,uM:7,bb:50,VM:100,isDefault:!0,q0:{background:"#080808",backgroundOpacity:.75,charEdgeStyle:0,color:"#fff",fontFamily:4,fontSizeIncrement:0,textOpacity:1,offset:1}};g.d(ieY,g.Lf);g.C=ieY.prototype;g.C.m6=function(){if(this.U||this.UJ){var a=this.L.vN();a&&!a.hP()&&a.B0()}else yHs(this,!1);g.Lf.prototype.m6.call(this)};
g.C.FI=function(){return this.S.C("html5_honor_caption_availabilities_in_audio_track")&&this.J!=="LIVE"&&this.J!=="SABR_LIVE"};
g.C.bM=function(){if(this.YG)return this.U||this.UJ;if(this.J==="HLS")return this.U;var a=this.getAudioTrack();if(this.FI()){if(!a.captionTracks.length)return!1;if(!this.B)return!0}a=q$y(a,g.xY(this.S));return a==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?!0:a==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"?iZ(this):VIn(this)||iZ(this)?!0:r3J(this)};
g.C.load=function(){g.Lf.prototype.load.call(this);this.BJ=this.getAudioTrack();if(this.B)this.T&&(this.EJ.clear(),this.U?Xch(this,!0):this.player.getPresentingPlayerType()!==3&&this.B.pH(this.T,"json3",this.Af),this.J!=="HLS"&&this.U||this.UJ||rS(this)||this.player.Bm("captionschanged",g.ZV(this.T)));else{var a;this.J==="OFFLINE"?a=new hp(this.player,this.videoData,this.getAudioTrack()):this.J==="SABR_LIVE"?a=new UZ(this.videoData.T,this.player):this.J==="HLS"?a=new mkh(this.player):this.J==="LIVE"?
a=new GB(this.videoData.T,this.player):this.J==="INNERTUBE"?a=new g.qM(this.player,this.videoData,this.getAudioTrack()):a=new g.ZI(this.player,this.videoData.O6,this.videoData.videoId,g.k2T(this.videoData),this.videoData.z$,this.videoData.eventId);this.B=a;g.U(this,this.B);this.B.DF(this.Af)}};
g.C.unload=function(){this.U&&this.T?Xch(this,!1):(this.e8&&g.x1(this.e8),this.player.f$("captions"),this.yP=[],this.B&&this.B.g$(),this.EJ.clear(),this.cJ&&this.player.GF(this.cJ),this.oo());g.Lf.prototype.unload.call(this);this.player.R5();this.player.Bm("captionschanged",{})};
g.C.create=function(){this.bM()&&this.load();var a;a:{var x,y,D;if(this.S.C("web_player_nitrate_promo_tooltip")&&((x=this.videoData.getPlayerResponse())==null?0:(y=x.captions)==null?0:(D=y.playerCaptionsTracklistRenderer)==null?0:D.enableTouchCaptionsNitrate)){var M,N;if(x=(a=this.videoData.getPlayerResponse())==null?void 0:(M=a.captions)==null?void 0:(N=M.playerCaptionsTracklistRenderer)==null?void 0:N.captionTracks)for(a=g.W(x),M=a.next();!M.done;M=a.next())if(M=M.value,M.kind==="asr"&&M.languageCode===
"en"){a=!0;break a}}a=!1}a&&this.L.publish("showpromotooltip",this.Y.element)};
g.C.mu=function(){var a=q$y(this.player.getAudioTrack(),g.xY(this.S));var x=a==="CAPTIONS_INITIAL_STATE_ON_REQUIRED"?V7(this,this.V):a==="CAPTIONS_INITIAL_STATE_OFF_REQUIRED"&&iZ(this)?OZ(this):VIn(this)||this.V||r3J(this)?V7(this,this.V):iZ(this)?OZ(this):null;if(this.J!=="HLS"&&this.U||this.UJ){var y=g.bn(this.B.T,!0);a=[];for(var D=0;D<y.length;D++){var M=y[D],N=g.WK("TRACK");N.setAttribute("kind","subtitles");N.setAttribute("label",g.dc(M));N.setAttribute("srclang",g.nO(M));N.setAttribute("id",
M.toString());this.UJ||N.setAttribute("src",this.B.Rl(M,"vtt"));M===x&&N.setAttribute("default","1");a.push(N)}x=this.L.vN();x.l6(a);a=x.Qn();this.iY&&this.OJ.Z(a.textTracks,"change",this.K4P)}else!this.T&&x&&bZ(this,x),this.player.Bm("onCaptionsTrackListChanged"),this.player.Ol("onApiChange")};
g.C.getTrackById=function(a){for(var x=g.bn(this.B.T,!0),y=0;y<x.length;y++)if(x[y].toString()===a)return x[y];return null};
g.C.K4P=function(){for(var a=this.L.vN().Qn().textTracks,x=null,y=0;y<a.length;y++)a[y].mode==="showing"&&(x=this.getTrackById(a[y].id));(this.loaded?this.T:null)!==x&&bZ(this,x,!0)};
g.C.Ht8=function(){var a;(a=this.B)==null||a.DF(this.Af)};
g.C.r1S=function(){!this.T&&this.U||this.unload()};
g.C.eh=function(a,x,y,D){if(a){var M;bes(this,(M=this.T)!=null?M:void 0);this.B.Dh()&&(this.yP=[],this.L.f$("captions"),oT(this.N1),this.EJ.reset());a:{M=this.EJ;D=D||0;y=RIh(M,a,y||0);a=[];try{for(var N=g.W(y),F=N.next();!F.done;F=N.next()){var c=F.value,J=c.trackData,G=c.Sf,Q=M.S.C("safari_live_drm_captions_fix");if(typeof J!=="string"){y=a;var S=y.concat;if(Q&&BUs(J))var K=Ykp(M,J,G);else{var L=M,w=x,Z=J,v=G,m=D;if(!ZeG(Z))throw Error("Invalid binary caption track data");L.T||(L.T=new YP(m,w));
K=L.T.J(Z,v)}var u=S.call(y,K)}else{if(J.substring(0,6)==="WEBVTT")var E=a.concat(Ykp(M,J,G));else{y=a;var h=y.concat;b:{w=L=void 0;Z=M;v=x;if(J[0]==="{")try{Z.T||(Z.T=new sZ(A3n(v)));var V=w=Z.T.J(J,G);break b}catch(DJ){g.mT(DJ);V=[];break b}var H=g.rp(J);if(!H||!H.firstChild){var j6=Error("Invalid caption track data");j6.params=J;throw j6;}if(H.firstChild.tagName==="timedtext"){if(Number(H.firstChild.getAttribute("format"))===3){Z.T||(Z.T=new lZ(A3n(v),Z.S));V=L=Z.T.J(H,G);break b}var e=Error("Unsupported subtitles format in web player (Format2)");
e.params=J;throw e;}if(H.firstChild.tagName==="transcript"){var as=Error("Unsupported subtitles format in web player (Format1)");as.params=J;throw as;}var z7=Error("Invalid caption track data");z7.params=J;throw z7;}E=h.call(y,V)}u=E}a=u}var Qq=a;break a}catch(DJ){g.Lc(M.logger,187101178,"Captions parsing failed: "+DJ.message+". ");M.clear();Qq=[];break a}Qq=void 0}x=Qq;x.length>0&&(Qq=this.T,this.G$(Qq,!!Qq,rS(this)?"g":this.V?"m":"s"));this.player.GF(x,void 0,this.J==="LIVE"||this.J==="SABR_LIVE");
!this.V||this.UJ||rS(this)||g.oF(this.S)||g.Ad(this.S)||g.f9(this.S)||this.S.tP==="shortspage"||this.player.isInline()||(g.x1(this.e8),x=KG7({uM:0,bb:5,VM:5,n4:2,textAlign:0,GM:0,lang:"ja"}),this.Cc=[x],Qq=[""," \u3092\u30af\u30ea\u30c3\u30af\u3057\u3066\u8a2d\u5b9a"],this.zt||(N=new g.Fp(g.mI()),g.U(this,N),this.zt=N.element),N=x.end-x.start,(F=g.dc(this.T))&&this.Cc.push(new n5(x.start,N,0,x.id,F)),this.Cc.push(new n5(x.start,N,0,x.id,Qq[0]),new n5(x.start,N,0,x.id,this.zt,!0),new n5(x.start,N,
0,x.id,Qq[1],!0)),this.player.GF(this.Cc),g.eN(this.e8));!this.V||this.UJ||rS(this)||(g.xY(this.S)?tp(this,!0):Xg(this,!0),this.BJ&&(this.BJ.U=this.T),this.player.R5());this.V=!1}};
g.C.onCueRangeEnter=function(a){this.yP.push(a);oT(this.N1)};
g.C.onCueRangeExit=function(a){g.Dk(this.yP,a);this.B instanceof GB&&this.B.Y&&this.player.qK([a]);oT(this.N1)};
g.C.getCaptionWindowContainerId=function(){return this.Y.element.id};
g.C.S9t=function(){xZn(this,this.Cc);this.Cc=null};
g.C.sN=function(){var a=this;if(!this.tf||!this.U){this.N1.stop();g.zhS(this.Gt);this.yP.sort(g.RF);var x=this.yP;if(this.cJ){var y=g.RH(x,function(N){return this.cJ.indexOf(N)===-1},this);
y.length&&(x=y)}x=g.W(x);for(y=x.next();!y.done;y=x.next())Idy(this,y.value);x=g.W(Object.entries(this.tP));var D=x.next();for(y={};!D.done;y={ZB:void 0,Wl:void 0},D=x.next()){var M=g.W(D.value);D=M.next().value;M=M.next().value;y.ZB=D;y.Wl=M;this.Gt[y.ZB]?(y.Wl.element.parentNode||(y.Wl instanceof Ap||y.Wl instanceof $P||g.os(this.tP,function(N){return function(F,c){c!==N.ZB&&F.B.params.uM===N.Wl.B.params.uM&&F.B.params.bb===N.Wl.B.params.bb&&F.B.params.VM===N.Wl.B.params.VM&&(F.dispose(),delete a.tP[c]);
return c===N.ZB}}(y),this),this.Y.element.appendChild(y.Wl.element)),y.Wl.Ii(this.Gt[y.ZB])):(y.Wl.dispose(),delete this.tP[y.ZB])}}};
g.C.PFR=function(){HeV(this,{},!0);this.player.Bm("captionssettingschanged")};
g.C.Fa=function(){var a=p5.q0;a={background:a.background,backgroundOpacity:a.backgroundOpacity,charEdgeStyle:a.charEdgeStyle,color:a.color,fontFamily:a.fontFamily,fontSizeIncrement:a.fontSizeIncrement,fontStyle:a.bold&&a.italic?3:a.bold?1:a.italic?2:0,textOpacity:a.textOpacity,windowColor:p5.windowColor,windowOpacity:p5.windowOpacity};var x=uzF()||{};x.background!=null&&(a.background=x.background);x.backgroundOverride!=null&&(a.backgroundOverride=x.backgroundOverride);x.backgroundOpacity!=null&&(a.backgroundOpacity=
x.backgroundOpacity);x.backgroundOpacityOverride!=null&&(a.backgroundOpacityOverride=x.backgroundOpacityOverride);x.charEdgeStyle!=null&&(a.charEdgeStyle=x.charEdgeStyle);x.charEdgeStyleOverride!=null&&(a.charEdgeStyleOverride=x.charEdgeStyleOverride);x.color!=null&&(a.color=x.color);x.colorOverride!=null&&(a.colorOverride=x.colorOverride);x.fontFamily!=null&&(a.fontFamily=x.fontFamily);x.fontFamilyOverride!=null&&(a.fontFamilyOverride=x.fontFamilyOverride);x.fontSizeIncrement!=null&&(a.fontSizeIncrement=
x.fontSizeIncrement);x.fontSizeIncrementOverride!=null&&(a.fontSizeIncrementOverride=x.fontSizeIncrementOverride);x.fontStyle!=null&&(a.fontStyle=x.fontStyle);x.fontStyleOverride!=null&&(a.fontStyleOverride=x.fontStyleOverride);x.textOpacity!=null&&(a.textOpacity=x.textOpacity);x.textOpacityOverride!=null&&(a.textOpacityOverride=x.textOpacityOverride);x.windowColor!=null&&(a.windowColor=x.windowColor);x.windowColorOverride!=null&&(a.windowColorOverride=x.windowColorOverride);x.windowOpacity!=null&&
(a.windowOpacity=x.windowOpacity);x.windowOpacityOverride!=null&&(a.windowOpacityOverride=x.windowOpacityOverride);return a};
g.C.wU=function(a,x){var y={};Object.assign(y,uzF());Object.assign(y,a);HeV(this,y,x);this.player.Bm("captionssettingschanged")};
g.C.oo=function(){!this.U&&this.loaded&&(g.hS(this.tP,function(a,x){a.dispose();delete this.tP[x]},this),this.sN())};
g.C.qY=function(a,x){switch(a){case "fontSize":if(isNaN(x))break;a=g.Dz(x,-2,4);this.wU({fontSizeIncrement:a});return a;case "reload":x&&!this.U&&bZ(this,this.T,!0);break;case "stickyLoading":x!==void 0&&this.S.V&&(g.xY(this.S)?tp(this,!!x):Xg(this,!!x));break;case "track":return apF(this,x);case "tracklist":return this.B?g.sk(g.bn(this.B.T,!(!x||!x.includeAsr)),function(y){return g.ZV(y)}):[];
case "translationLanguages":return this.B?this.B.N.map(function(y){return Object.assign({},y)}):[];
case "sampleSubtitles":this.U||x===void 0||yHs(this,!!x);break;case "sampleSubtitlesCustomized":this.U||yHs(this,!!x,x);break;case "recommendedTranslationLanguages":return g.nu();case "defaultTranslationSourceTrackIndices":return this.B?this.B.V:[]}};
g.C.getOptions=function(){var a="reload fontSize track tracklist translationLanguages sampleSubtitle".split(" ");this.S.V&&a.push("stickyLoading");return a};
g.C.Ut=function(){var a=this.T;if(this.L.Fg("captions")){if(this.S.C("html5_modify_caption_vss_logging")){var x;return(a=(x=this.videoData.jq)!=null?x:null)?{cc:g.Css(a)}:{}}if(a)return x=a.vssId,a.translationLanguage&&x&&(x="t"+x+"."+g.nO(a)),{cc:x}}return{}};
g.C.svG=function(){this.isSubtitlesOn()?(g.xY(this.S)?tp(this,!1):Xg(this,!1),bes(this),bZ(this,null,!0)):this.Vk()};
g.C.Vk=function(){var a=rS(this)||!this.T?V7(this,!0):this.T;a&&this.YL(a.vssId,"m");this.isSubtitlesOn()||bZ(this,rS(this)||!this.T?V7(this,!0):this.T,!0)};
g.C.isSubtitlesOn=function(){return!!this.loaded&&!!this.T&&!rS(this)};
g.C.mGJ=function(){var a=rS(this);iZ(this,a)?bZ(this,this.getAudioTrack().T,!1):this.videoData.captionTracks.length&&(this.loaded&&this.unload(),this.FI()&&(this.V=!1,this.T=null,this.B&&(this.B.dispose(),this.B=null)),this.bM()&&(a?bZ(this,V7(this,!1),!1):this.load()))};
g.C.xg=function(a){a&&(this.dS={top:a.top,right:a.right,bottom:a.bottom,left:a.left,width:1-a.left-a.right,height:1-a.top-a.bottom},this.Y.element.style.top=this.dS.top*100+"%",this.Y.element.style.left=this.dS.left*100+"%",this.Y.element.style.width=this.dS.width*100+"%",this.Y.element.style.height=this.dS.height*100+"%",this.Y.element.style.position="absolute",a=eI7(this))&&(this.Y.element.style.width=a.width+"px",this.Y.element.style.height=a.height+"px")};
g.C.onVideoDataChange=function(a,x){a==="newdata"&&(this.videoData=x,this.loaded&&this.unload(),this.V=!1,this.T=null,this.B&&(this.B.dispose(),this.B=null,this.player.Bm("captionschanged",{})),this.bM()&&this.load())};
g.C.getAudioTrack=function(){return this.player.getAudioTrack()};
g.C.i1P=function(){var a=this.L.vN();a&&!a.hP()&&a.B0();this.L.isFullscreen()?(this.U=this.YG=!0,this.loaded&&this.mu()):(this.YG=this.S.controlsType==="3",this.U=UFh(this));bZ(this,this.T)};
g.C.TR=function(){var a,x,y,D=(a=this.videoData.getPlayerResponse())==null?void 0:(x=a.captions)==null?void 0:(y=x.playerCaptionsTracklistRenderer)==null?void 0:y.openTranscriptCommand;D&&this.player.uY("innertubeCommand",D)};
g.C.G$=function(a,x,y){var D=/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,M="";a&&(M=a.vssId,M=M.replace(D,""));var N="";a&&a.getId()&&(N=a.getId()||"");a&&a.getXtags()&&(a=a.getXtags(),a=a.replace(D,""),N=N.concat(";"+a));this.L.G$(x?M:"",x?N:"",y)};
g.C.YL=function(a,x){a=(a||"").replace(/&|,|:|;|(\n)|(\s)|(\/)|(\\)/gm,"");a.length>0&&this.L.YL(a,x)};g.Kf("captions",ieY);})(_yt_player);
