(function(g){var window=this;'use strict';var BPp=function(a){a.publish("autonavvisibility")},h9y=function(a,x){a.uY("onAutonavCoundownStarted",x)},$Zh=function(a){return a.isBackground()&&a.Cf()},fpt=function(a){var x,y,D;
return a==null?void 0:(x=a.playerOverlays)==null?void 0:(y=x.playerOverlayRenderer)==null?void 0:(D=y.autoplay)==null?void 0:D.playerOverlayAutoplayRenderer},M0=function(a){var x=a.j(),y=x.U;
g.O.call(this,{W:"a",G:"ytp-autonav-suggestion-card",X:{href:"{{url}}",target:y?x.BJ:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},K:[{W:"div",wS:["ytp-autonav-endscreen-upnext-thumbnail","ytp-autonav-thumbnail-small"],X:{style:"{{background}}"},K:[{W:"div",X:{"aria-label":"{{timestamp}}"},wS:["ytp-autonav-timestamp"],PJ:"{{duration}}"},{W:"div",wS:["ytp-autonav-live-stamp"],PJ:"\u30e9\u30a4\u30d6"},
{W:"div",wS:["ytp-autonav-upcoming-stamp"],PJ:"\u914d\u4fe1\u4e88\u5b9a"},{W:"div",G:"ytp-autonav-list-overlay",K:[{W:"div",G:"ytp-autonav-mix-text",PJ:"\u30df\u30c3\u30af\u30b9\u30ea\u30b9\u30c8"},{W:"div",G:"ytp-autonav-mix-icon"}]}]},{W:"div",wS:["ytp-autonav-endscreen-upnext-title","ytp-autonav-title-card"],PJ:"{{title}}"},{W:"div",wS:["ytp-autonav-endscreen-upnext-author","ytp-autonav-author-card"],PJ:"{{author}}"},{W:"div",wS:["ytp-autonav-endscreen-upnext-author","ytp-autonav-view-and-date-card"],
PJ:"{{views_and_publish_time}}"}]});this.L=a;this.suggestion=null;this.T=y;this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress)},N0=function(a,x){x=x===void 0?!1:x;
g.O.call(this,{W:"div",G:"ytp-autonav-endscreen-countdown-overlay"});var y=this;this.D=x;this.cancelCommand=this.N=void 0;this.J=0;this.container=new g.O({W:"div",G:"ytp-autonav-endscreen-countdown-container"});g.U(this,this.container);this.container.a7(this.element);x=a.j();var D=x.U;this.L=a;this.suggestion=null;this.onVideoDataChange("newdata",this.L.getVideoData());this.Z(a,"videodatachange",this.onVideoDataChange);this.T=new g.O({W:"div",G:"ytp-autonav-endscreen-upnext-container",X:{"aria-label":"{{aria_label}}",
"data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}","data-is-upcoming":"{{is_upcoming}}"},K:[{W:"div",G:"ytp-autonav-endscreen-upnext-header"},{W:"div",G:"ytp-autonav-endscreen-upnext-alternative-header",PJ:"{{autoplayAlternativeHeader}}"},{W:"a",G:"ytp-autonav-endscreen-link-container",X:{href:"{{url}}",target:D?x.BJ:""},K:[{W:"div",G:"ytp-autonav-endscreen-upnext-thumbnail",X:{style:"{{background}}"},K:[{W:"div",X:{"aria-label":"{{timestamp}}"},wS:["ytp-autonav-timestamp"],
PJ:"{{duration}}"},{W:"div",wS:["ytp-autonav-live-stamp"],PJ:"\u30e9\u30a4\u30d6"},{W:"div",wS:["ytp-autonav-upcoming-stamp"],PJ:"\u914d\u4fe1\u4e88\u5b9a"}]},{W:"div",G:"ytp-autonav-endscreen-video-info",K:[{W:"div",G:"ytp-autonav-endscreen-premium-badge"},{W:"div",G:"ytp-autonav-endscreen-upnext-title",PJ:"{{title}}"},{W:"div",G:"ytp-autonav-endscreen-upnext-author",PJ:"{{author}}"},{W:"div",G:"ytp-autonav-view-and-date",PJ:"{{views_and_publish_time}}"},{W:"div",G:"ytp-autonav-author-and-view",
PJ:"{{author_and_views}}"}]}]}]});g.U(this,this.T);this.T.a7(this.container.element);D||this.Z(this.T.QP("ytp-autonav-endscreen-link-container"),"click",this.QR);this.L.createClientVe(this.container.element,this,115127);this.L.createClientVe(this.T.QP("ytp-autonav-endscreen-link-container"),this,115128);this.overlay=new g.O({W:"div",G:"ytp-autonav-overlay"});g.U(this,this.overlay);this.overlay.a7(this.container.element);this.B=new g.O({W:"div",G:"ytp-autonav-endscreen-button-container"});g.U(this,
this.B);this.B.a7(this.container.element);this.cancelButton=new g.O({W:"button",wS:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-cancel-button","ytp-autonav-endscreen-upnext-button-rounded"],X:{"aria-label":"\u81ea\u52d5\u518d\u751f\u3092\u30ad\u30e3\u30f3\u30bb\u30eb\u3059\u308b"},PJ:"\u30ad\u30e3\u30f3\u30bb\u30eb"});g.U(this,this.cancelButton);this.cancelButton.a7(this.B.element);this.cancelButton.listen("click",this.HH,this);this.L.createClientVe(this.cancelButton.element,
this,115129);this.playButton=new g.O({W:"a",wS:["ytp-autonav-endscreen-upnext-button","ytp-autonav-endscreen-upnext-play-button","ytp-autonav-endscreen-upnext-button-rounded"],X:{href:"{{url}}",role:"button","aria-label":"\u6b21\u306e\u52d5\u753b\u3092\u518d\u751f"},PJ:"\u4eca\u3059\u3050\u518d\u751f"});g.U(this,this.playButton);this.playButton.a7(this.B.element);this.playButton.listen("click",this.QR,this);this.L.createServerVe(this.playButton.element,this.playButton,!0);(x=this.L.getVideoData())&&
gkh(this,x);this.U=new g.Id(function(){R97(y)},500);
g.U(this,this.U);this.tZ();this.Z(a,"autonavvisibility",this.tZ);this.L.C("web_autonav_color_transition")&&(this.Z(a,"autonavchange",this.i_),this.Z(a,"onAutonavCoundownStarted",this.ti6))},FY=function(a){var x=a.L.cq(!0,a.L.isFullscreen());
g.Gt(a.container.element,"ytp-autonav-endscreen-small-mode",a.Zu(x));g.Gt(a.container.element,"ytp-autonav-endscreen-is-premium",!!a.suggestion&&!!a.suggestion.ZKJ);g.Gt(a.L.getRootNode(),"ytp-autonav-endscreen-cancelled-state",!a.L.A6());g.Gt(a.L.getRootNode(),"countdown-running",a.Ny());g.Gt(a.container.element,"ytp-player-content",a.L.A6());g.F7(a.overlay.element,{width:x.width+"px"});if(!a.Ny()){a.L.A6()?Y8y(a,Math.round(AHp(a)/1E3)):Y8y(a);x=!!a.suggestion&&!!a.suggestion.He;var y=a.L.A6()||
!x;g.Gt(a.container.element,"ytp-autonav-endscreen-upnext-alternative-header-only",!y&&x);g.Gt(a.container.element,"ytp-autonav-endscreen-upnext-no-alternative-header",y&&!x);a.B.lO(a.L.A6());g.Gt(a.element,"ytp-enable-w2w-color-transitions",UZP(a))}},R97=function(a){var x=AHp(a),y=Math,D=y.min;
var M=a.J?Date.now()-a.J:0;y=D.call(y,M,x);Y8y(a,Math.ceil((x-y)/1E3));x-y<=500&&a.Ny()?a.select(!0):a.Ny()&&a.U.start()},AHp=function(a){if(a.L.isFullscreen()){var x;
a=(x=a.L.getVideoData())==null?void 0:x.qq;return a===-1||a===void 0?8E3:a}return a.L.xv()>=0?a.L.xv():g.ts(a.L.j().experiments,"autoplay_time")||1E4},gkh=function(a,x){x=x.getWatchNextResponse();
var y,D;x=(y=fpt(x))==null?void 0:(D=y.nextButton)==null?void 0:D.buttonRenderer;a.N=x==null?void 0:x.navigationEndpoint;y=x==null?void 0:x.trackingParams;a.playButton&&y&&a.L.setTrackingParams(a.playButton.element,y)},UZP=function(a){var x;
return!((x=a.L.getVideoData())==null||!x.watchToWatchTransitionRenderer)},Y8y=function(a,x){x=x===void 0?-1:x;
a=a.T.QP("ytp-autonav-endscreen-upnext-header");g.hi(a);if(x>=0){x=String(x);var y="$SECONDS \u79d2\u5f8c\u306b\u6b21\u306e\u52d5\u753b\u3092\u518d\u751f".match(RegExp("\\$SECONDS","gi"))[0],D="$SECONDS \u79d2\u5f8c\u306b\u6b21\u306e\u52d5\u753b\u3092\u518d\u751f".indexOf(y);if(D>=0){a.appendChild(g.s$("$SECONDS \u79d2\u5f8c\u306b\u6b21\u306e\u52d5\u753b\u3092\u518d\u751f".slice(0,D)));var M=g.WK("span");g.NE(M,"ytp-autonav-endscreen-upnext-header-countdown-number");g.RZ(M,x);a.appendChild(M);a.appendChild(g.s$("$SECONDS \u79d2\u5f8c\u306b\u6b21\u306e\u52d5\u753b\u3092\u518d\u751f".slice(D+
y.length)));return}}g.RZ(a,"\u6b21\u306e\u52d5\u753b")},zO=function(a,x){g.O.call(this,{W:"div",
wS:["html5-endscreen","ytp-player-content",x||"base-endscreen"]});this.created=!1;this.player=a},cT=function(a){g.O.call(this,{W:"div",
wS:["ytp-upnext","ytp-player-content"],X:{"aria-label":"{{aria_label}}"},K:[{W:"div",G:"ytp-cued-thumbnail-overlay-image",X:{style:"{{background}}"}},{W:"span",G:"ytp-upnext-top",K:[{W:"span",G:"ytp-upnext-header",PJ:"\u6b21\u306e\u52d5\u753b"},{W:"span",G:"ytp-upnext-title",PJ:"{{title}}"},{W:"span",G:"ytp-upnext-author",PJ:"{{author}}"}]},{W:"a",G:"ytp-upnext-autoplay-icon",X:{role:"button",href:"{{url}}","aria-label":"\u6b21\u306e\u52d5\u753b\u3092\u518d\u751f"},K:[{W:"svg",X:{height:"100%",version:"1.1",
viewBox:"0 0 72 72",width:"100%"},K:[{W:"circle",G:"ytp-svg-autoplay-circle",X:{cx:"36",cy:"36",fill:"#fff","fill-opacity":"0.3",r:"31.5"}},{W:"circle",G:"ytp-svg-autoplay-ring",X:{cx:"-36",cy:"36","fill-opacity":"0",r:"33.5",stroke:"#FFFFFF","stroke-dasharray":"211","stroke-dashoffset":"-211","stroke-width":"4",transform:"rotate(-90)"}},{W:"path",G:"ytp-svg-fill",X:{d:"M 24,48 41,36 24,24 V 48 z M 44,24 v 24 h 4 V 24 h -4 z"}}]}]},{W:"span",G:"ytp-upnext-bottom",K:[{W:"span",G:"ytp-upnext-cancel"},
{W:"span",G:"ytp-upnext-paused",PJ:"\u81ea\u52d5\u518d\u751f\u306f\u4e00\u6642\u505c\u6b62\u3055\u308c\u3066\u3044\u307e\u3059"}]}]});this.api=a;this.cancelButton=null;this.N=this.QP("ytp-svg-autoplay-ring");this.J=this.notification=this.T=this.suggestion=null;this.U=new g.Id(this.eJ,5E3,this);this.B=0;var x=this.QP("ytp-upnext-cancel");this.cancelButton=new g.O({W:"button",wS:["ytp-upnext-cancel-button","ytp-button"],X:{tabindex:"0","aria-label":"\u81ea\u52d5\u518d\u751f\u3092\u30ad\u30e3\u30f3\u30bb\u30eb\u3059\u308b"},
PJ:"\u30ad\u30e3\u30f3\u30bb\u30eb"});g.U(this,this.cancelButton);this.cancelButton.listen("click",this.Ks,this);this.cancelButton.a7(x);this.cancelButton&&this.api.createClientVe(this.cancelButton.element,this,115129);g.U(this,this.U);this.api.createClientVe(this.element,this,18788);x=this.QP("ytp-upnext-autoplay-icon");this.Z(x,"click",this.Sm);this.api.createClientVe(x,this,115130);this.fk();this.Z(a,"autonavvisibility",this.fk);this.Z(a,"mdxnowautoplaying",this.KKc);this.Z(a,"mdxautoplaycanceled",
this.SK7);g.Gt(this.element,"ytp-upnext-mobile",this.api.j().B)},H47=function(a,x){if(x)return x;
if(a.api.isFullscreen()){var y;a=(y=a.api.getVideoData())==null?void 0:y.qq;return a===-1||a===void 0?8E3:a}return a.api.xv()>=0?a.api.xv():g.ts(a.api.j().experiments,"autoplay_time")||1E4},i4V=function(a,x){x=H47(a,x);
var y=Math,D=y.min;var M=(0,g.lY)()-a.B;y=D.call(y,M,x);x=x===0?1:Math.min(y/x,1);a.N.setAttribute("stroke-dashoffset",""+-211*(x+1));x>=1&&a.Ny()&&a.api.getPresentingPlayerType()!==3?a.select(!0):a.Ny()&&a.T.start()},oY=function(a){zO.call(this,a,"autonav-endscreen");
this.overlay=this.videoData=null;this.table=new g.O({W:"div",G:"ytp-suggestion-panel",K:[{W:"div",wS:["ytp-autonav-endscreen-upnext-header","ytp-autonav-endscreen-more-videos"],PJ:"\u305d\u306e\u4ed6\u306e\u52d5\u753b"}]});this.Y=new g.O({W:"div",G:"ytp-suggestions-container"});this.videos=[];this.J=null;this.N=this.D=!1;this.B=new N0(this.player);g.U(this,this.B);this.B.a7(this.element);a.getVideoData().S8?this.T=this.B:(this.T=new cT(a),g.f1(this.player,this.T.element,4),g.U(this,this.T));this.overlay=
new g.O({W:"div",G:"ytp-autonav-overlay-cancelled-state"});g.U(this,this.overlay);this.overlay.a7(this.element);this.U=new g.zW(this);g.U(this,this.U);g.U(this,this.table);this.table.a7(this.element);this.table.show();g.U(this,this.Y);this.Y.a7(this.table.element);this.hide()},Jr=function(a){var x=a.A6();
x!==a.N&&(a.N=x,BPp(a.player),a.N?(a.B!==a.T&&a.B.hide(),a.table.hide()):(a.B!==a.T&&a.B.show(),a.table.show()))},O4P=function(a){zO.call(this,a,"videowall-endscreen");
var x=this;this.L=a;this.stills=[];this.J=this.videoData=null;this.U=this.D=!1;this.Y=null;g.zt(this.element,"modern-videowall-endscreen");this.B=new g.zW(this);g.U(this,this.B);this.N=new g.Id(function(){g.zt(x.element,"ytp-show-tiles")},0);
g.U(this,this.N);this.table=new g.Fp({W:"div",G:"ytp-modern-endscreen-content"});g.U(this,this.table);this.table.a7(this.element);a.getVideoData().S8?this.T=new N0(a,!0):this.T=new cT(a);g.U(this,this.T);g.f1(this.player,this.T.element,4);a.createClientVe(this.element,this,158789);this.hide()},GO=function(a){return g.gj(a.player)&&a.Z_()&&!a.J},QO=function(a){var x=a.A6();
x!==a.D&&(a.D=x,BPp(a.player))},V2F=function(a){zO.call(this,a,"subscribecard-endscreen");
this.T=new g.O({W:"div",G:"ytp-subscribe-card",K:[{W:"img",G:"ytp-author-image",X:{src:"{{profilePicture}}"}},{W:"div",G:"ytp-subscribe-card-right",K:[{W:"div",G:"ytp-author-name",PJ:"{{author}}"},{W:"div",G:"html5-subscribe-button-container"}]}]});g.U(this,this.T);this.T.a7(this.element);var x=a.getVideoData();this.subscribeButton=new g.pf("\u767b\u9332",null,"\u767b\u9332\u89e3\u9664",null,!0,!1,x.kW,x.subscribed,"trailer-endscreen",null,a,!1);g.U(this,this.subscribeButton);this.subscribeButton.a7(this.T.QP("html5-subscribe-button-container"));
this.Z(a,"videodatachange",this.rS);this.rS();this.hide()},SG=function(a){var x=a.j(),y=g.DY||g.Er?{style:"will-change: opacity"}:void 0,D=x.U,M=["ytp-videowall-still"];
x.B&&M.push("ytp-videowall-show-text");g.O.call(this,{W:"a",wS:M,X:{href:"{{url}}",target:D?x.BJ:"","aria-label":"{{aria_label}}","data-is-live":"{{is_live}}","data-is-list":"{{is_list}}","data-is-mix":"{{is_mix}}"},K:[{W:"div",G:"ytp-videowall-still-image",X:{style:"{{background}}"}},{W:"span",G:"ytp-videowall-still-info",X:{"aria-hidden":"true"},K:[{W:"span",G:"ytp-videowall-still-info-bg",K:[{W:"span",G:"ytp-videowall-still-info-content",X:y,K:[{W:"span",G:"ytp-videowall-still-info-title",PJ:"{{title}}"},
{W:"span",G:"ytp-videowall-still-info-author",PJ:"{{author_and_views}}"},{W:"span",G:"ytp-videowall-still-info-live",PJ:"\u30e9\u30a4\u30d6"},{W:"span",G:"ytp-videowall-still-info-duration",PJ:"{{duration}}"}]}]}]},{W:"span",wS:["ytp-videowall-still-listlabel-regular","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},K:[{W:"span",G:"ytp-videowall-still-listlabel-icon"},"\u518d\u751f\u30ea\u30b9\u30c8",{W:"span",G:"ytp-videowall-still-listlabel-length",K:[" (",{W:"span",PJ:"{{playlist_length}}"},
")"]}]},{W:"span",wS:["ytp-videowall-still-listlabel-mix","ytp-videowall-still-listlabel"],X:{"aria-hidden":"true"},K:[{W:"span",G:"ytp-videowall-still-listlabel-mix-icon"},"\u30df\u30c3\u30af\u30b9\u30ea\u30b9\u30c8",{W:"span",G:"ytp-videowall-still-listlabel-length",PJ:" (50+)"}]}]});this.suggestion=null;this.B=D;this.api=a;this.T=new g.zW(this);g.U(this,this.T);this.listen("click",this.onClick);this.listen("keypress",this.onKeyPress);this.T.Z(a,"videodatachange",this.onVideoDataChange);a.createServerVe(this.element,
this);this.onVideoDataChange()},K8=function(a){zO.call(this,a,"videowall-endscreen");
var x=this;this.L=a;this.J=0;this.stills=[];this.U=this.videoData=null;this.N=this.Y=!1;this.V=null;this.B=new g.zW(this);g.U(this,this.B);this.D=new g.Id(function(){g.zt(x.element,"ytp-show-tiles")},0);
g.U(this,this.D);var y=new g.O({W:"button",wS:["ytp-button","ytp-endscreen-previous"],X:{"aria-label":"\u524d\u3078"},K:[g.Lq()]});g.U(this,y);y.a7(this.element);y.listen("click",this.PV,this);this.table=new g.Fp({W:"div",G:"ytp-endscreen-content"});g.U(this,this.table);this.table.a7(this.element);y=new g.O({W:"button",wS:["ytp-button","ytp-endscreen-next"],X:{"aria-label":"\u6b21\u3078"},K:[g.wD()]});g.U(this,y);y.a7(this.element);y.listen("click",this.dP,this);a.getVideoData().S8?this.T=new N0(a,
!0):this.T=new cT(a);g.U(this,this.T);g.f1(this.player,this.T.element,4);a.createClientVe(this.element,this,158789);this.hide()},L8=function(a){return g.gj(a.player)&&a.Z_()&&!a.U},wF=function(a){var x=a.A6();
x!==a.Y&&(a.Y=x,BPp(a.player))},rHt=function(a,x){g.O.call(this,{W:"button",
wS:["ytp-watch-on-youtube-button","ytp-button"],PJ:"{{content}}"});this.L=a;this.buttonType=this.buttonType=x;this.m3();this.buttonType===2&&g.zt(this.element,"ytp-continue-watching-button");this.listen("click",this.onClick);this.listen("videodatachange",this.m3);this.lO(!0)},C8=function(a){zO.call(this,a,"watch-again-on-youtube-endscreen");
this.watchButton=new rHt(a,1);g.U(this,this.watchButton);this.watchButton.a7(this.element);g.TOT(a)&&(this.T=new g.X0(a),g.U(this,this.T),this.B=new g.O({W:"div",wS:["ytp-watch-again-on-youtube-endscreen-more-videos-container"],X:{tabIndex:"-1"},K:[this.T]}),g.U(this,this.B),this.T.a7(this.B.element),this.B.a7(this.element));a.createClientVe(this.element,this,156914);this.hide()},p7y=function(a){g.Lf.call(this,a);
var x=this;this.endScreen=null;this.T=this.B=this.J=!1;this.listeners=new g.zW(this);g.U(this,this.listeners);var y=a.j();a.isEmbedsShortsMode()?this.endScreen=new C8(a):t2h(a)?(this.J=!0,X7p(this),this.T?this.endScreen=new oY(a):y.C("delhi_modern_endscreen")?this.endScreen=new O4P(a):this.endScreen=new K8(a)):y.WO?this.endScreen=new V2F(a):this.endScreen=new zO(a);g.U(this,this.endScreen);g.f1(a,this.endScreen.element,4);b47(this);this.listeners.Z(a,"videodatachange",this.onVideoDataChange,this);
this.listeners.Z(a,g.Y6("endscreen"),function(D){x.onCueRangeEnter(D)});
this.listeners.Z(a,g.A9("endscreen"),function(D){x.onCueRangeExit(D)})},X7p=function(a){var x=a.player.getVideoData();
if(!x||a.T===x.El&&a.B===x.S8)return!1;a.T=x.El;a.B=x.S8;return!0},t2h=function(a){a=a.j();
return a.AK&&!a.WO&&!a.disableOrganicUi},b47=function(a){a.player.f$("endscreen");
var x=a.player.getVideoData();x=new g.gr(Math.max((x.lengthSeconds-10)*1E3,0),0x8000000000000,{id:"preload",namespace:"endscreen"});var y=new g.gr(0x8000000000000,0x8000000000000,{id:"load",priority:8,namespace:"endscreen"});a.player.GF([x,y])};
g.uS.prototype.xv=g.YG(6,function(){return this.app.xv()});
g.KF.prototype.xv=g.YG(5,function(){return this.getVideoData().DZ});
g.n1.prototype.Pr=g.YG(4,function(a){this.b$().Pr(a)});
g.OE.prototype.Pr=g.YG(3,function(a){this.UX!==a&&(this.UX=a,this.Ds())});
g.d(M0,g.O);M0.prototype.select=function(){this.L.p_(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.SV||void 0)&&this.L.logClick(this.element)};
M0.prototype.onClick=function(a){g.zC(a,this.L,this.T,this.suggestion.sessionData||void 0)&&this.select()};
M0.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};g.d(N0,g.O);g.C=N0.prototype;g.C.PW=function(a){this.suggestion!==a&&(this.suggestion=a,g.y3(this.T,a),this.playButton.updateValue("url",this.suggestion.CB()),FY(this))};
g.C.Ny=function(){return this.J>0};
g.C.Sh=function(){this.Ny()||(this.J=Date.now(),R97(this),h9y(this.L,AHp(this)),g.Gt(this.L.getRootNode(),"countdown-running",this.Ny()))};
g.C.mO=function(){this.zf();R97(this);var a=this.T.QP("ytp-autonav-endscreen-upnext-header");a&&g.RZ(a,"\u6b21\u306e\u52d5\u753b")};
g.C.zf=function(){this.Ny()&&(this.U.stop(),this.J=0)};
g.C.select=function(a){this.L.nextVideo(!1,a===void 0?!1:a);this.zf()};
g.C.QR=function(a){g.zC(a,this.L)&&(a.currentTarget===this.playButton.element?this.L.logClick(this.playButton.element):a.currentTarget===this.T.QP("ytp-autonav-endscreen-link-container")&&(a=this.T.QP("ytp-autonav-endscreen-link-container"),this.L.logVisibility(a,!0),this.L.logClick(a)),this.N?(this.L.uY("innertubeCommand",this.N),this.zf()):this.select())};
g.C.HH=function(){this.L.logClick(this.cancelButton.element);g.Wi(this.L,!0);this.cancelCommand&&this.L.uY("innertubeCommand",this.cancelCommand)};
g.C.onVideoDataChange=function(a,x){gkh(this,x);a=x.getWatchNextResponse();var y,D;a=(y=fpt(a))==null?void 0:(D=y.cancelButton)==null?void 0:D.buttonRenderer;this.cancelCommand=a==null?void 0:a.command};
g.C.ti6=function(a){if(UZP(this)){var x=this.L.getVideoData().watchToWatchTransitionRenderer,y=x==null?void 0:x.fromColorPaletteDark;x=x==null?void 0:x.toColorPaletteDark;if(y&&x){var D=this.element;D.style.setProperty("--w2w-start-background-color",g.gl(y.surgeColor));D.style.setProperty("--w2w-start-primary-text-color",g.gl(y.primaryTitleColor));D.style.setProperty("--w2w-start-secondary-text-color",g.gl(y.secondaryTitleColor));D.style.setProperty("--w2w-end-background-color",g.gl(x.surgeColor));
D.style.setProperty("--w2w-end-primary-text-color",g.gl(x.primaryTitleColor));D.style.setProperty("--w2w-end-secondary-text-color",g.gl(x.secondaryTitleColor));D.style.setProperty("--w2w-animation-duration",a+"ms")}g.Gt(this.element,"ytp-w2w-animate",!0)}};
g.C.i_=function(a){this.L.C("web_autonav_color_transition")&&a!==2&&g.Gt(this.element,"ytp-w2w-animate",!1)};
g.C.tZ=function(){var a=this.L.A6();this.D&&this.d0!==a&&this.lO(a);FY(this);this.L.logVisibility(this.container.element,a);this.L.logVisibility(this.cancelButton.element,a);this.L.logVisibility(this.T.QP("ytp-autonav-endscreen-link-container"),a);this.L.logVisibility(this.playButton.element,a)};
g.C.Zu=function(a){return a.width<400||a.height<459};g.d(zO,g.O);g.C=zO.prototype;g.C.create=function(){this.created=!0};
g.C.destroy=function(){this.created=!1};
g.C.Z_=function(){return!1};
g.C.A6=function(){return!1};
g.C.b3=function(){return!1};g.d(cT,g.O);g.C=cT.prototype;g.C.eJ=function(){this.notification&&(this.U.stop(),this.WN(this.J),this.J=null,this.notification.close(),this.notification=null)};
g.C.PW=function(a){this.suggestion=a;g.y3(this,a,"hqdefault.jpg")};
g.C.fk=function(){this.lO(this.api.A6());this.api.logVisibility(this.element,this.api.A6());this.api.logVisibility(this.QP("ytp-upnext-autoplay-icon"),this.api.A6());this.cancelButton&&this.api.logVisibility(this.cancelButton.element,this.api.A6())};
g.C.nx1=function(){window.focus();this.eJ()};
g.C.Sh=function(a){var x=this;this.Ny()||(g.Ma("a11y-announce","\u6b21\u306e\u52d5\u753b "+this.suggestion.title),this.B=(0,g.lY)(),this.T=new g.Id(function(){i4V(x,a)},25),i4V(this,a),h9y(this.api,H47(this,a)));
g.o9(this.element,"ytp-upnext-autoplay-paused")};
g.C.hide=function(){g.O.prototype.hide.call(this)};
g.C.Ny=function(){return!!this.T};
g.C.mO=function(){this.zf();this.B=(0,g.lY)();i4V(this);g.zt(this.element,"ytp-upnext-autoplay-paused")};
g.C.zf=function(){this.Ny()&&(this.T.dispose(),this.T=null)};
g.C.select=function(a){a=a===void 0?!1:a;if(this.api.j().C("autonav_notifications")&&a&&window.Notification&&typeof document.hasFocus==="function"){var x=Notification.permission;x==="default"?Notification.requestPermission():x!=="granted"||document.hasFocus()||(this.eJ(),this.notification=new Notification("\u6b21\u306e\u52d5\u753b",{body:this.suggestion.title,icon:this.suggestion.LJ()}),this.J=this.Z(this.notification,"click",this.nx1),this.U.start())}this.zf();this.api.nextVideo(!1,a)};
g.C.Sm=function(a){!g.g1(this.cancelButton.element,a.target)&&g.zC(a,this.api)&&(this.api.A6()&&this.api.logClick(this.QP("ytp-upnext-autoplay-icon")),this.select())};
g.C.Ks=function(){this.api.A6()&&this.cancelButton&&this.api.logClick(this.cancelButton.element);g.Wi(this.api,!0)};
g.C.KKc=function(a){this.api.getPresentingPlayerType();this.show();this.Sh(a)};
g.C.SK7=function(){this.api.getPresentingPlayerType();this.zf();this.hide()};
g.C.m6=function(){this.zf();this.eJ();g.O.prototype.m6.call(this)};g.d(oY,zO);g.C=oY.prototype;g.C.create=function(){zO.prototype.create.call(this);this.U.Z(this.player,"appresize",this.Am);this.U.Z(this.player,"onVideoAreaChange",this.Am);this.U.Z(this.player,"videodatachange",this.onVideoDataChange);this.U.Z(this.player,"autonavchange",this.JZ);this.U.Z(this.player,"onAutonavCancelled",this.TN);this.onVideoDataChange()};
g.C.show=function(){zO.prototype.show.call(this);(this.D||this.J&&this.J!==this.videoData.clientPlaybackNonce)&&g.Wi(this.player,!1);g.gj(this.player)&&this.Z_()&&!this.J?(Jr(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||$Zh(this.player.SZ())&&this.player.C("web_player_pip_logging_fix")?this.T.select(!0):this.T.Sh():this.videoData.autonavState===3&&this.T.mO()):(g.Wi(this.player,!0),Jr(this));this.Am()};
g.C.hide=function(){zO.prototype.hide.call(this);this.T.mO();Jr(this)};
g.C.Am=function(){var a=this.player.cq(!0,this.player.isFullscreen());Jr(this);FY(this.B);g.Gt(this.element,"ytp-autonav-cancelled-small-mode",this.Zu(a));g.Gt(this.element,"ytp-autonav-cancelled-tiny-mode",this.xu(a));g.Gt(this.element,"ytp-autonav-cancelled-mini-mode",a.width<=400||a.height<=360);this.overlay&&g.F7(this.overlay.element,{width:a.width+"px"});if(!this.N)for(a=0;a<this.videos.length;a++)g.Gt(this.videos[a].element,"ytp-suggestion-card-with-margin",a%2===1)};
g.C.onVideoDataChange=function(){var a=this.player.getVideoData();if(this.videoData!==a&&a){this.videoData=a;a=this.videoData.suggestions;var x=g.Fc(this.videoData);x&&(this.T.PW(x),this.T!==this.B&&this.B.PW(x));if(a&&a.length)for(x=0;x<IpP.length;++x){var y=IpP[x];if(a&&a[y]){this.videos[x]=new M0(this.player);var D=this.videos[x];y=a[y];D.suggestion!==y&&(D.suggestion=y,g.y3(D,y));g.U(this,this.videos[x]);this.videos[x].a7(this.Y.element)}}this.Am()}};
g.C.JZ=function(a){a===1?(this.D=!1,this.J=this.videoData.clientPlaybackNonce,this.T.zf(),this.d0&&this.Am()):(this.D=!0,this.A6()&&(a===2?this.T.Sh():a===3&&this.T.mO()))};
g.C.TN=function(a){a?this.JZ(1):(this.J=null,this.D=!1)};
g.C.Z_=function(){return this.videoData.autonavState!==1};
g.C.Zu=function(a){return(a.width<910||a.height<459)&&!this.xu(a)&&!(a.width<=400||a.height<=360)};
g.C.xu=function(a){return a.width<800&&!(a.width<=400||a.height<=360)};
g.C.A6=function(){return this.d0&&g.gj(this.player)&&this.Z_()&&!this.J};
var IpP=[1,3,2,4];g.d(O4P,zO);g.C=O4P.prototype;g.C.create=function(){zO.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.yg();this.B.Z(this.player,"appresize",this.yg);this.B.Z(this.player,"onVideoAreaChange",this.yg);this.B.Z(this.player,"videodatachange",this.onVideoDataChange);this.B.Z(this.player,"autonavchange",this.cR);this.B.Z(this.player,"onAutonavCancelled",this.BV);a=this.videoData.autonavState;a!==this.Y&&this.cR(a);this.B.Z(this.element,"transitionend",this.cV)};
g.C.destroy=function(){g.h6(this.B);g.CD(this.stills);this.stills=[];zO.prototype.destroy.call(this);g.o9(this.element,"ytp-show-tiles");this.N.stop();this.Y=this.videoData.autonavState};
g.C.Z_=function(){return this.videoData.autonavState!==1};
g.C.show=function(){var a=this.d0;zO.prototype.show.call(this);g.o9(this.element,"ytp-show-tiles");this.player.j().B?g.a9(this.N):this.N.start();(this.U||this.J&&this.J!==this.videoData.clientPlaybackNonce)&&g.Wi(this.player,!1);GO(this)?(QO(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||$Zh(this.player.SZ())&&this.player.C("web_player_pip_logging_fix")?this.T.select(!0):this.T.Sh():this.videoData.autonavState===3&&this.T.mO()):(g.Wi(this.player,!0),QO(this));a!==this.d0&&
this.player.logVisibility(this.element,!0)};
g.C.hide=function(){var a=this.d0;zO.prototype.hide.call(this);this.T.mO();QO(this);a!==this.d0&&this.player.logVisibility(this.element,!1)};
g.C.cV=function(a){a.target===this.element&&this.yg()};
g.C.yg=function(){var a,x,y,D;var M=((a=this.videoData)==null?0:(x=a.suggestions)==null?0:x.length)?(y=this.videoData)==null?void 0:y.suggestions:[(D=this.videoData)==null?void 0:g.Fc(D)];if(M.length){x=this.L.cq(!0,this.L.isFullscreen());a=Math.floor((x.width-64+16)/(g.Dz(x.width*.27,250,450)+16));x=Math.min(3,Math.floor((x.height-64)/((x.width-64-(a-1)*16)/a*.5625+70)));g.Jg(this.element,["ytp-modern-endscreen-limit-rows-1","ytp-modern-endscreen-limit-rows-2","ytp-modern-endscreen-limit-rows-3"]);
g.zt(this.element,"ytp-modern-endscreen-limit-rows-"+x);g.Gt(this.element,"ytp-modern-endscreen-single-item",a===1);g.Gt(this.element,"ytp-modern-endscreen-row-0",x===0);a=this.table.element;a.ariaLive="polite";this.T.PW(g.Fc(this.videoData));this.T instanceof N0&&FY(this.T);g.Gt(this.element,"ytp-endscreen-takeover",GO(this));QO(this);x=0;a.ariaBusy="true";y=M.length;for(D=0;D<y;D++){var N=D%y,F=this.stills[D];F||(F=new g.j5(this.player),this.stills[D]=F,a.appendChild(F.element));g.ilS(F,M[N]);x++}this.stills.length=
x}};
g.C.onVideoDataChange=function(){var a=this.player.getVideoData(1);this.videoData!==a&&(a!=null&&g.Fc(a)?(this.videoData=a,this.yg()):this.player.AP("missg",{vid:(a==null?void 0:a.videoId)||"",cpn:(a==null?void 0:a.clientPlaybackNonce)||""}))};
g.C.b3=function(){return this.T.Ny()};
g.C.cR=function(a){a===1?(this.U=!1,this.J=this.videoData.clientPlaybackNonce,this.T.zf(),this.d0&&this.yg()):(this.U=!0,this.d0&&GO(this)&&(a===2?this.T.Sh():a===3&&this.T.mO()))};
g.C.BV=function(a){if(a){for(a=0;a<this.stills.length;a++)this.L.logVisibility(this.stills[a].element,!0);this.cR(1)}else this.J=null,this.U=!1;this.yg()};
g.C.A6=function(){return this.d0&&GO(this)};g.d(V2F,zO);V2F.prototype.rS=function(){var a=this.player.getVideoData();this.T.update({profilePicture:a.profilePicture,author:a.author});this.subscribeButton.channelId=a.kW;var x=this.subscribeButton;a.subscribed?x.T():x.B()};g.d(SG,g.O);SG.prototype.select=function(){this.api.p_(this.suggestion.videoId,this.suggestion.sessionData,this.suggestion.playlistId,void 0,void 0,this.suggestion.SV||void 0)&&this.api.logClick(this.element)};
SG.prototype.onClick=function(a){if(g.Br(this.api.j())&&this.api.C("web_player_log_click_before_generating_ve_conversion_params")){this.api.logClick(this.element);var x=this.suggestion.CB(),y={};g.Bi(this.api,y);x=g.sS(x,y);g.c4(x,this.api,a)}else g.zC(a,this.api,this.B,this.suggestion.sessionData||void 0)&&this.select()};
SG.prototype.onKeyPress=function(a){switch(a.keyCode){case 13:case 32:a.defaultPrevented||(this.select(),a.preventDefault())}};
SG.prototype.onVideoDataChange=function(){var a=this.api.getVideoData(),x=this.api.j();this.B=a.gF?!1:x.U};g.d(K8,zO);g.C=K8.prototype;g.C.create=function(){zO.prototype.create.call(this);var a=this.player.getVideoData();a&&(this.videoData=a);this.lq();this.B.Z(this.player,"appresize",this.lq);this.B.Z(this.player,"onVideoAreaChange",this.lq);this.B.Z(this.player,"videodatachange",this.onVideoDataChange);this.B.Z(this.player,"autonavchange",this.A9);this.B.Z(this.player,"onAutonavCancelled",this.AB);a=this.videoData.autonavState;a!==this.V&&this.A9(a);this.B.Z(this.element,"transitionend",this.nF)};
g.C.destroy=function(){g.h6(this.B);g.CD(this.stills);this.stills=[];zO.prototype.destroy.call(this);g.o9(this.element,"ytp-show-tiles");this.D.stop();this.V=this.videoData.autonavState};
g.C.Z_=function(){return this.videoData.autonavState!==1};
g.C.show=function(){var a=this.d0;zO.prototype.show.call(this);g.o9(this.element,"ytp-show-tiles");this.player.j().B?g.a9(this.D):this.D.start();(this.N||this.U&&this.U!==this.videoData.clientPlaybackNonce)&&g.Wi(this.player,!1);L8(this)?(wF(this),this.videoData.autonavState===2?this.player.getVisibilityState()===3||$Zh(this.player.SZ())&&this.player.C("web_player_pip_logging_fix")?this.T.select(!0):this.T.Sh():this.videoData.autonavState===3&&this.T.mO()):(g.Wi(this.player,!0),wF(this));a!==this.d0&&
this.player.logVisibility(this.element,!0)};
g.C.hide=function(){var a=this.d0;zO.prototype.hide.call(this);this.T.mO();wF(this);a!==this.d0&&this.player.logVisibility(this.element,!1)};
g.C.nF=function(a){a.target===this.element&&this.lq()};
g.C.lq=function(){var a,x,y,D;var M=((a=this.videoData)==null?0:(x=a.suggestions)==null?0:x.length)?(y=this.videoData)==null?void 0:y.suggestions:[(D=this.videoData)==null?void 0:g.Fc(D)];if(M.length){g.zt(this.element,"ytp-endscreen-paginate");var N=this.L.cq(!0,this.L.isFullscreen());if(a=g.wj(this.L))a=a.PO()?48:32,N.width-=a*2;var F=N.width/N.height;D=96/54;x=a=2;var c=Math.max(N.width/96,2),J=Math.max(N.height/54,2);y=M.length;var G=y*4;for(G-=4;G>0&&(a<c||x<J);){var Q=a/2,S=x/2,K=a<=c-2&&G>=
S*4,L=x<=J-2&&G>=Q*4;if((Q+1)/S*D/F>F/(Q/(S+1)*D)&&L)G-=Q*4,x+=2;else if(K)G-=S*4,a+=2;else if(L)G-=Q*4,x+=2;else break}D=!1;G>=12&&y*4-G<=6&&(x>=4||a>=4)&&(D=!0);G=a*96;c=x*54;F=G/c<F?N.height/c:N.width/G;F=Math.min(F,2);G=Math.floor(Math.min(N.width,G*F));c=Math.floor(Math.min(N.height,c*F));N=this.table.element;N.ariaLive="polite";g.wU(N,G,c);g.F7(N,{marginLeft:G/-2+"px",marginTop:c/-2+"px"});this.T.PW(g.Fc(this.videoData));this.T instanceof N0&&FY(this.T);g.Gt(this.element,"ytp-endscreen-takeover",
L8(this));wF(this);G+=4;c+=4;F=0;N.ariaBusy="true";for(J=0;J<a;J++)for(Q=0;Q<x;Q++)if(S=F,L=0,D&&J>=a-2&&Q>=x-2?L=1:Q%2===0&&J%2===0&&(Q<2&&J<2?Q===0&&J===0&&(L=2):L=2),S=g.Mk(S+this.J,y),L!==0){K=this.stills[F];K||(K=new SG(this.player),this.stills[F]=K,N.appendChild(K.element));var w=Math.floor(c*Q/x),Z=Math.floor(G*J/a),v=Math.floor(c*(Q+L)/x)-w-4,m=Math.floor(G*(J+L)/a)-Z-4;g.Qv(K.element,Z,w);g.wU(K.element,m,v);g.F7(K.element,"transitionDelay",(Q+J)/20+"s");g.Gt(K.element,"ytp-videowall-still-mini",
L===1);g.Gt(K.element,"ytp-videowall-still-large",L>2);L=Math.max(m,v);g.Gt(K.element,"ytp-videowall-still-round-large",L>=256);g.Gt(K.element,"ytp-videowall-still-round-medium",L>96&&L<256);g.Gt(K.element,"ytp-videowall-still-round-small",L<=96);S=M[S];K.suggestion!==S&&(K.suggestion=S,L=K.api.j(),w=g.FR(K.element,"ytp-videowall-still-large")?"hqdefault.jpg":"mqdefault.jpg",g.y3(K,S,w),g.Br(L)&&!K.api.C("web_player_log_click_before_generating_ve_conversion_params")&&(L=S.CB(),w={},g.Gb(K.api,"addEmbedsConversionTrackingParams",
[w]),L=g.sS(L,w),K.updateValue("url",L)),(S=(S=S.sessionData)&&S.itct)&&K.api.setTrackingParams(K.element,S));F++}N.ariaBusy="false";g.Gt(this.element,"ytp-endscreen-paginate",F<y);for(M=this.stills.length-1;M>=F;M--)a=this.stills[M],g.f0(a.element),g.wg(a);this.stills.length=F}};
g.C.onVideoDataChange=function(){var a=this.player.getVideoData(1);this.videoData!==a&&(a!=null&&g.Fc(a)?(this.J=0,this.videoData=a,this.lq()):this.player.AP("missg",{vid:(a==null?void 0:a.videoId)||"",cpn:(a==null?void 0:a.clientPlaybackNonce)||""}))};
g.C.dP=function(){this.J+=this.stills.length;this.lq()};
g.C.PV=function(){this.J-=this.stills.length;this.lq()};
g.C.b3=function(){return this.T.Ny()};
g.C.A9=function(a){a===1?(this.N=!1,this.U=this.videoData.clientPlaybackNonce,this.T.zf(),this.d0&&this.lq()):(this.N=!0,this.d0&&L8(this)&&(a===2?this.T.Sh():a===3&&this.T.mO()))};
g.C.AB=function(a){if(a){for(a=0;a<this.stills.length;a++)this.L.logVisibility(this.stills[a].element,!0);this.A9(1)}else this.U=null,this.N=!1;this.lq()};
g.C.A6=function(){return this.d0&&L8(this)};g.d(rHt,g.O);g.C=rHt.prototype;g.C.m3=function(){switch(this.buttonType){case 1:var a="YouTube \u3067\u3082\u3046\u4e00\u5ea6\u898b\u308b";var x=156915;break;case 2:a="YouTube \u3067\u8996\u8074\u3092\u7d9a\u884c";x=156942;break;default:a="YouTube \u3067\u8996\u8074\u3092\u7d9a\u884c",x=156942}this.update({content:a});this.L.hasVe(this.element)&&this.L.destroyVe(this.element);this.L.createClientVe(this.element,this,x)};
g.C.onClick=function(a){this.L.C("web_player_log_click_before_generating_ve_conversion_params")&&this.L.logClick(this.element);g.c4(this.getVideoUrl(),this.L,a);this.L.C("web_player_log_click_before_generating_ve_conversion_params")||this.L.logClick(this.element)};
g.C.getVideoUrl=function(){var a=!0;switch(this.buttonType){case 1:a=!0;break;case 2:a=!1}a=this.L.getVideoUrl(a,!1,!1,!0);var x=this.L.j();if(g.Br(x)){var y={};g.Br(x)&&g.Gb(this.L,"addEmbedsConversionTrackingParams",[y]);a=g.sS(a,y)}return a};
g.C.logVisibility=function(){this.L.logVisibility(this.element,this.d0&&this.BJ)};
g.C.show=function(){g.O.prototype.show.call(this);this.logVisibility()};
g.C.hide=function(){g.O.prototype.hide.call(this);this.logVisibility()};
g.C.Se=function(a){g.O.prototype.Se.call(this,a);this.logVisibility()};g.d(C8,zO);C8.prototype.hasSuggestions=function(){var a;return(a=this.T)==null?void 0:a.hasSuggestions()};
C8.prototype.show=function(){if(this.player.getPlayerState()!==3){zO.prototype.show.call(this);var a=this.B;if(a){var x=this.T.hasSuggestions();g.Gt(this.element,"ytp-shorts-branded-ui",x);x?a.show():a.hide()}var y;(y=g.wj(this.player))==null||y.Pr(!0);this.player.logVisibility(this.element,!0);this.watchButton.Se(!0)}};
C8.prototype.hide=function(){zO.prototype.hide.call(this);var a;(a=g.wj(this.player))==null||a.Pr(!1);this.player.logVisibility(this.element,!1);this.watchButton.Se(!1)};g.d(p7y,g.Lf);g.C=p7y.prototype;g.C.bM=function(){var a=this.player.getVideoData(),x=a.mutedAutoplay&&(a.limitedPlaybackDurationInSeconds>0||a.endSeconds>0||a.mutedAutoplayDurationMode!==2);if(this.player.isEmbedsShortsMode()&&!x)return!0;var y;var D=!!((a==null?0:g.Fc(a))||(a==null?0:(y=a.suggestions)==null?0:y.length));D=!t2h(this.player)||D;a=a.Ph;y=this.player.EV();return D&&!a&&!y&&!x};
g.C.A6=function(){return this.endScreen.A6()};
g.C.XJP=function(){return this.A6()?this.endScreen.b3():!1};
g.C.m6=function(){this.player.f$("endscreen");g.Lf.prototype.m6.call(this)};
g.C.load=function(){var a=this.player.getVideoData();var x=a.transitionEndpointAtEndOfStream;if(x&&x.videoId){var y=this.player.s6().nt.get("heartbeat"),D=g.Fc(a);!D||x.videoId!==D.videoId||a.y7?(this.player.p_(x.videoId,void 0,void 0,!0,!0,x),y&&y.oQ("HEARTBEAT_ACTION_TRIGGER_AT_STREAM_END","HEARTBEAT_ACTION_TRANSITION_REASON_HAS_NEW_STREAM_TRANSITION_ENDPOINT"),a=!0):a=!1}else a=!1;a||(g.Lf.prototype.load.call(this),this.endScreen.show())};
g.C.unload=function(){g.Lf.prototype.unload.call(this);this.endScreen.hide();this.endScreen.destroy()};
g.C.onCueRangeEnter=function(a){this.bM()&&(this.endScreen.created||this.endScreen.create(),a.getId()==="load"&&this.load())};
g.C.onCueRangeExit=function(a){a.getId()==="load"&&this.loaded&&this.unload()};
g.C.onVideoDataChange=function(){b47(this);this.J&&X7p(this)&&(this.endScreen&&(this.endScreen.hide(),this.endScreen.created&&this.endScreen.destroy(),this.endScreen.dispose()),this.T?this.endScreen=new oY(this.player):this.endScreen=new K8(this.player),g.U(this,this.endScreen),g.f1(this.player,this.endScreen.element,4))};g.Kf("endscreen",p7y);})(_yt_player);
